import type { CategoryKey, EquipmentKey, TrackingKey } from "./constants";

export type SeedExercise = {
  name: string;
  category: CategoryKey;
  equipment: EquipmentKey[];
  muscles: string[];
  /** Une phrase : de quoi il s'agit. */
  description: string;
  /** Le déroulé du mouvement, une étape par entrée. */
  steps: string[];
  /** Points de vigilance et erreurs fréquentes. */
  cues: string;
  /** Coût énergétique en MET. Absent = valeur par défaut de la catégorie. */
  met?: number;
  tracking: TrackingKey;
};

/**
 * Bibliothèque de départ : orientée poids libres, médecine ball / slam ball,
 * mouvement fonctionnel et exercices à deux. Peu de muscu isolée.
 * Le coach peut en ajouter autant qu'il veut depuis l'app.
 */
export const EXERCISE_LIBRARY: SeedExercise[] = [
  /* ----------------------------- ÉCHAUFFEMENT ----------------------------- */
  {
    name: "Rameur — échauffement",
    category: "echauffement",
    equipment: ["rameur"],
    muscles: ["Corps entier", "Cardio"],
    description: "Rame à allure facile pour monter en température et mobiliser le dos.",
    steps: [
      "Règle les sangles sur l'avant du pied, assieds-toi genoux fléchis, attrape la poignée.",
      "Pousse d'abord fort avec les jambes, puis bascule le buste en arrière, puis tire la poignée vers le bas des côtes.",
      "Reviens dans l'ordre inverse : tends les bras, penche le buste en avant, puis plie les jambes.",
      "Enchaîne à allure tranquille pendant toute la durée prévue.",
    ],
    cues: "Ordre du mouvement : jambes → buste → bras. Retour : bras → buste → jambes. Cadence 20-24 coups/min.",
    met: 4.8,
    tracking: "time_distance",
  },
  {
    name: "Vélo — échauffement",
    category: "echauffement",
    equipment: ["velo"],
    muscles: ["Jambes", "Cardio"],
    description: "Pédalage progressif, résistance légère, pour lancer la machine.",
    steps: [
      "Règle la selle : jambe presque tendue quand la pédale est en bas.",
      "Démarre à résistance minimale pendant 2 minutes, juste pour dérouiller.",
      "Monte la résistance d'un cran toutes les 2 minutes.",
      "Termine à une allure où tu peux encore parler sans être essoufflée.",
    ],
    cues: "Commence très facile, monte la résistance toutes les 2 minutes. Tu dois pouvoir parler.",
    tracking: "time_distance",
  },
  {
    name: "Corde à sauter — échauffement",
    category: "echauffement",
    equipment: ["corde_a_sauter"],
    muscles: ["Mollets", "Cardio", "Coordination"],
    description: "Petits sauts légers pour réveiller les chevilles et le système nerveux.",
    steps: [
      "Règle la longueur : un pied au milieu de la corde, les poignées doivent arriver aux aisselles.",
      "Coudes près du corps, mains à hauteur de hanches.",
      "Fais tourner la corde avec les poignets seulement et saute de 2-3 cm.",
      "Si tu accroches, repars immédiatement : c'est normal au début.",
    ],
    cues: "Reste sur l'avant du pied, coudes près du corps, ce sont les poignets qui tournent.",
    met: 8.8,
    tracking: "time",
  },
  {
    name: "Mobilité articulaire complète",
    category: "echauffement",
    equipment: ["aucun"],
    muscles: ["Corps entier"],
    description: "Cercles de chevilles, genoux, hanches, buste, épaules, poignets, cou.",
    steps: [
      "Debout, fais 10 cercles avec chaque cheville, dans un sens puis dans l'autre.",
      "Remonte : genoux, puis hanches (cercles de bassin), puis buste.",
      "Termine par les épaules, les poignets et de lentes rotations de la tête.",
      "Augmente l'amplitude au fil des répétitions.",
    ],
    cues: "10 rotations par articulation, de bas en haut. Amplitude progressive, jamais forcée.",
    met: 2.5,
    tracking: "time",
  },
  {
    name: "Montées de genoux",
    category: "echauffement",
    equipment: ["aucun"],
    muscles: ["Fléchisseurs de hanche", "Cardio"],
    description: "Course sur place genoux hauts, rythme soutenu.",
    steps: [
      "Debout, buste droit, mains ouvertes à hauteur de nombril.",
      "Monte un genou jusqu'à toucher ta main, repose le pied et alterne.",
      "Accélère jusqu'à un rythme de course.",
    ],
    cues: "Genou à hauteur de hanche, buste droit, appuis dynamiques sur l'avant du pied.",
    met: 8,
    tracking: "time",
  },
  {
    name: "Talons-fesses",
    category: "echauffement",
    equipment: ["aucun"],
    muscles: ["Ischio-jambiers", "Cardio"],
    description: "Course sur place en ramenant les talons vers les fessiers.",
    steps: [
      "Debout, mains posées sur les fessiers.",
      "Ramène un talon pour venir toucher ta main, puis alterne.",
      "Garde le buste droit et accélère progressivement.",
    ],
    cues: "Bassin bien droit, ne cambre pas. Rythme rapide et léger.",
    met: 8,
    tracking: "time",
  },
  {
    name: "Pas chassés latéraux",
    category: "echauffement",
    equipment: ["aucun"],
    muscles: ["Fessiers", "Adducteurs"],
    description: "Déplacements latéraux en position semi-fléchie.",
    steps: [
      "Fléchis les genoux comme pour un demi-squat, mains devant toi.",
      "Pousse avec le pied extérieur pour te déplacer sur le côté.",
      "Fais 5 pas dans un sens, 5 dans l'autre, sans jamais te relever.",
    ],
    cues: "Reste bas, ne croise pas les pieds, pousse fort avec la jambe extérieure.",
    tracking: "time",
  },
  {
    name: "Activation fessiers élastique",
    category: "echauffement",
    equipment: ["elastique"],
    muscles: ["Moyen fessier"],
    description: "Pas latéraux (monster walk) avec un élastique au-dessus des genoux.",
    steps: [
      "Place l'élastique juste au-dessus des genoux, pieds largeur de bassin.",
      "Fléchis légèrement les genoux et penche un peu le buste en avant.",
      "Fais de petits pas sur le côté en gardant l'élastique tendu.",
      "5 pas à droite, 5 pas à gauche, sans laisser les genoux rentrer.",
    ],
    cues: "Genoux qui poussent vers l'extérieur, petits pas, tension permanente dans l'élastique.",
    met: 3.5,
    tracking: "reps",
  },
  {
    name: "Pont fessier au sol",
    category: "echauffement",
    equipment: ["tapis"],
    muscles: ["Fessiers", "Ischio-jambiers"],
    description: "Allongée sur le dos, on décolle le bassin en serrant les fessiers.",
    steps: [
      "Allongée sur le dos, genoux pliés, pieds à plat près des fessiers.",
      "Pousse dans les talons pour décoller le bassin jusqu'à aligner genoux-hanches-épaules.",
      "Serre les fessiers 1 seconde en haut.",
      "Redescends lentement sans poser complètement entre les répétitions.",
    ],
    cues: "Pousse dans les talons, serre les fessiers en haut 1 seconde, ne cambre pas le bas du dos.",
    met: 3,
    tracking: "reps",
  },
  {
    name: "Squat au poids du corps",
    category: "echauffement",
    equipment: ["aucun"],
    muscles: ["Quadriceps", "Fessiers"],
    description: "Squat lent et contrôlé pour préparer les hanches et les genoux.",
    steps: [
      "Pieds largeur d'épaules, pointes légèrement vers l'extérieur, bras tendus devant.",
      "Pousse les fesses en arrière comme pour t'asseoir sur une chaise.",
      "Descends jusqu'à ce que les cuisses soient parallèles au sol.",
      "Remonte en poussant dans les talons.",
    ],
    cues: "Pieds largeur d'épaules, poitrine haute, descends jusqu'à ce que les cuisses soient parallèles au sol.",
    met: 3.5,
    tracking: "reps",
  },
  {
    name: "Fentes marchées d'échauffement",
    category: "echauffement",
    equipment: ["aucun"],
    muscles: ["Quadriceps", "Fessiers", "Psoas"],
    description: "Fentes avant en avançant, sans charge, amplitude progressive.",
    steps: [
      "Debout, mains sur les hanches.",
      "Fais un grand pas en avant et descends jusqu'à ce que le genou arrière frôle le sol.",
      "Pousse sur le talon avant pour te relever et enchaîne avec l'autre jambe.",
      "Avance ainsi sur 8 à 10 pas.",
    ],
    cues: "Grand pas, genou arrière proche du sol, buste vertical.",
    tracking: "reps",
  },
  {
    name: "Rotations du buste",
    category: "echauffement",
    equipment: ["aucun"],
    muscles: ["Obliques", "Dos"],
    description: "Bassin fixe, on fait tourner le haut du corps de gauche à droite.",
    steps: [
      "Debout, pieds largeur de bassin, bras relâchés le long du corps.",
      "Fais pivoter les épaules vers la droite en laissant les bras suivre par inertie.",
      "Reviens et enchaîne vers la gauche, sans bouger le bassin.",
    ],
    cues: "Bras relâchés, ce sont les épaules qui emmènent. Bassin qui ne bouge pas.",
    met: 2.5,
    tracking: "reps",
  },
  {
    name: "Cercles de bras",
    category: "echauffement",
    equipment: ["aucun"],
    muscles: ["Épaules"],
    description: "Grands cercles avant puis arrière pour ouvrir les épaules.",
    steps: [
      "Debout, bras tendus sur les côtés à hauteur d'épaules.",
      "Fais 15 grands cercles vers l'avant, en cherchant l'amplitude maximale.",
      "Puis 15 cercles vers l'arrière.",
    ],
    cues: "Bras tendus, amplitude maximale, 15 dans chaque sens.",
    met: 2.8,
    tracking: "reps",
  },
  {
    name: "Inchworm",
    category: "echauffement",
    equipment: ["tapis"],
    muscles: ["Ischio-jambiers", "Épaules", "Gainage"],
    description: "Debout, mains au sol, on marche en planche puis on revient.",
    steps: [
      "Debout, penche-toi pour poser les mains au sol, jambes aussi tendues que possible.",
      "Avance les mains une par une jusqu'à te retrouver en position de planche.",
      "Fais le chemin inverse en ramenant les mains vers les pieds.",
      "Redresse-toi et recommence.",
    ],
    cues: "Jambes aussi tendues que possible à l'aller, gainage serré en position de planche.",
    tracking: "reps",
  },

  /* ---------------------------- FORCE / POIDS LIBRES ---------------------- */
  {
    name: "Goblet squat",
    category: "force",
    equipment: ["haltere", "kettlebell"],
    muscles: ["Quadriceps", "Fessiers", "Gainage"],
    description: "Squat avec un haltère ou une kettlebell tenu contre la poitrine.",
    steps: [
      "Tiens l'haltère à deux mains contre la poitrine, coudes pointés vers le sol.",
      "Pieds largeur d'épaules, pointes légèrement vers l'extérieur.",
      "Descends en poussant les fesses en arrière, buste le plus vertical possible.",
      "Descends jusqu'à ce que les coudes touchent l'intérieur des genoux, puis remonte en poussant dans les talons.",
    ],
    cues: "Coudes à l'intérieur des genoux en bas, poitrine haute, poids dans tout le pied.",
    tracking: "reps_weight",
  },
  {
    name: "Squat sumo haltère",
    category: "force",
    equipment: ["haltere", "kettlebell"],
    muscles: ["Fessiers", "Adducteurs", "Quadriceps"],
    description: "Squat pieds très écartés, pointes vers l'extérieur, haltère entre les jambes.",
    steps: [
      "Écarte les pieds bien plus large que les épaules, pointes ouvertes à 45°.",
      "Tiens l'haltère à deux mains, bras tendus entre les jambes.",
      "Descends droit vers le bas en gardant le buste vertical.",
      "Remonte en poussant le sol vers l'extérieur avec les pieds.",
    ],
    cues: "Genoux dans l'axe des pieds, descends bas, pousse le sol vers l'extérieur.",
    tracking: "reps_weight",
  },
  {
    name: "Squat bulgare",
    category: "force",
    equipment: ["haltere", "banc"],
    muscles: ["Quadriceps", "Fessiers"],
    description: "Fente arrière surélevée, pied arrière posé sur un banc.",
    steps: [
      "Pose le dessus du pied arrière sur un banc, l'autre pied environ 60 cm devant.",
      "Un haltère dans chaque main, bras le long du corps.",
      "Descends verticalement en pliant la jambe avant, genou arrière vers le sol.",
      "Remonte en poussant dans le talon avant. Fais toutes les répétitions avant de changer de jambe.",
    ],
    cues: "Pied avant assez loin du banc, descends verticalement, ne pars pas en avant.",
    tracking: "reps_weight",
  },
  {
    name: "Front squat haltères",
    category: "force",
    equipment: ["haltere"],
    muscles: ["Quadriceps", "Fessiers", "Gainage"],
    description: "Haltères posés sur les épaules, squat complet.",
    steps: [
      "Monte un haltère sur chaque épaule, coudes hauts pointés vers l'avant.",
      "Pieds largeur d'épaules, gaine les abdos et bloque ta respiration.",
      "Descends en gardant le buste bien vertical.",
      "Remonte et souffle en passant le point le plus dur.",
    ],
    cues: "Coudes hauts, buste vertical, respiration bloquée à la descente.",
    tracking: "reps_weight",
  },
  {
    name: "Squat sauté lesté",
    category: "force",
    equipment: ["haltere", "gilet_leste"],
    muscles: ["Quadriceps", "Fessiers", "Explosivité"],
    description: "Squat avec une charge légère, terminé par un saut.",
    steps: [
      "Prends une charge légère (haltères le long du corps ou gilet lesté).",
      "Descends en demi-squat.",
      "Remonte de façon explosive jusqu'à décoller du sol.",
      "Réceptionne genoux souples et enchaîne directement.",
    ],
    cues: "Charge légère uniquement. Réception silencieuse, genoux souples.",
    met: 7,
    tracking: "reps_weight",
  },
  {
    name: "Fentes avant haltères",
    category: "force",
    equipment: ["haltere"],
    muscles: ["Quadriceps", "Fessiers"],
    description: "Fentes alternées avec un haltère dans chaque main.",
    steps: [
      "Debout, un haltère dans chaque main, bras le long du corps.",
      "Fais un grand pas en avant et descends jusqu'à ce que le genou arrière frôle le sol.",
      "Pousse sur le talon avant pour revenir debout.",
      "Alterne les jambes à chaque répétition.",
    ],
    cues: "Grand pas, genou arrière qui frôle le sol, pousse sur le talon avant pour remonter.",
    tracking: "reps_weight",
  },
  {
    name: "Fentes arrière haltères",
    category: "force",
    equipment: ["haltere"],
    muscles: ["Fessiers", "Ischio-jambiers"],
    description: "On recule au lieu d'avancer : plus doux pour les genoux, plus fessiers.",
    steps: [
      "Debout, un haltère dans chaque main.",
      "Recule d'un grand pas et pose la pointe du pied arrière.",
      "Descends jusqu'à ce que le genou arrière frôle le sol.",
      "Ramène le pied arrière pour revenir debout, puis alterne.",
    ],
    cues: "Le pied arrière se pose sur la pointe, le buste reste droit.",
    tracking: "reps_weight",
  },
  {
    name: "Fentes marchées lestées",
    category: "force",
    equipment: ["haltere", "sac_leste"],
    muscles: ["Quadriceps", "Fessiers", "Équilibre"],
    description: "Enchaînement de fentes en avançant sur une distance donnée.",
    steps: [
      "Charge en main (haltères) ou sur les épaules (sac lesté).",
      "Fais un grand pas en avant et descends en fente.",
      "Au lieu de revenir en arrière, ramène le pied arrière devant pour la fente suivante.",
      "Avance ainsi sur la distance ou le nombre de pas prévus.",
    ],
    cues: "Regard loin devant, gainage serré, pas trop rapide.",
    met: 5.5,
    tracking: "reps_weight",
  },
  {
    name: "Fentes latérales",
    category: "force",
    equipment: ["haltere", "kettlebell"],
    muscles: ["Adducteurs", "Fessiers"],
    description: "Grand pas sur le côté, on s'assoit sur la jambe fléchie.",
    steps: [
      "Debout, charge tenue à deux mains devant la poitrine.",
      "Fais un grand pas sur le côté et pousse les fesses en arrière.",
      "Plie la jambe du côté du pas, l'autre reste tendue.",
      "Pousse sur la jambe fléchie pour revenir au centre, puis change de côté.",
    ],
    cues: "La jambe opposée reste tendue, pied à plat, fesses en arrière.",
    tracking: "reps_weight",
  },
  {
    name: "Soulevé de terre jambes tendues (haltères)",
    category: "force",
    equipment: ["haltere"],
    muscles: ["Ischio-jambiers", "Fessiers", "Lombaires"],
    description: "Charnière de hanche avec haltères, jambes quasi tendues.",
    steps: [
      "Debout, un haltère dans chaque main devant les cuisses, genoux à peine fléchis.",
      "Pousse les fesses loin en arrière en laissant les haltères glisser le long des jambes.",
      "Descends jusqu'à sentir l'étirement à l'arrière des cuisses, dos toujours plat.",
      "Remonte en serrant les fessiers, sans cambrer en haut.",
    ],
    cues: "Dos plat, fesses vers l'arrière, les haltères frôlent les jambes. Étirement à l'arrière des cuisses.",
    tracking: "reps_weight",
  },
  {
    name: "Soulevé de terre unilatéral",
    category: "force",
    equipment: ["haltere", "kettlebell"],
    muscles: ["Ischio-jambiers", "Fessiers", "Équilibre"],
    description: "Charnière sur une jambe, l'autre part en arrière dans l'alignement.",
    steps: [
      "Charge dans la main opposée à la jambe d'appui.",
      "Fléchis légèrement le genou d'appui et penche le buste en avant.",
      "Laisse la jambe libre partir en arrière dans l'alignement du dos.",
      "Descends jusqu'à l'horizontale puis remonte en serrant le fessier.",
    ],
    cues: "Hanches carrées (le bassin ne s'ouvre pas), dos plat, mouvement lent.",
    tracking: "reps_weight",
  },
  {
    name: "Hip thrust",
    category: "force",
    equipment: ["haltere", "barre", "banc"],
    muscles: ["Fessiers"],
    description: "Dos appuyé sur un banc, on pousse le bassin vers le plafond.",
    steps: [
      "Assieds-toi au sol, le haut du dos calé contre un banc, pieds à plat.",
      "Pose la charge sur le pli des hanches et tiens-la à deux mains.",
      "Pousse dans les talons pour monter le bassin jusqu'à l'horizontale.",
      "Serre les fessiers 1 seconde puis redescends sans poser complètement.",
    ],
    cues: "Menton rentré, côtes basses, serre les fessiers 1 s en haut sans cambrer.",
    tracking: "reps_weight",
  },
  {
    name: "Hip thrust une jambe",
    category: "force",
    equipment: ["banc", "poids_du_corps"],
    muscles: ["Fessiers", "Gainage"],
    description: "Version unilatérale du hip thrust, jambe libre fléchie ou tendue.",
    steps: [
      "Haut du dos calé contre le banc, un seul pied au sol.",
      "Ramène l'autre genou vers la poitrine, ou tends la jambe vers l'avant.",
      "Pousse dans le talon d'appui pour monter le bassin à l'horizontale.",
      "Redescends lentement en gardant le bassin bien droit.",
    ],
    cues: "Bassin bien horizontal, ne laisse pas une hanche descendre.",
    tracking: "reps_weight",
  },
  {
    name: "Swing kettlebell",
    category: "force",
    equipment: ["kettlebell"],
    muscles: ["Fessiers", "Ischio-jambiers", "Dos", "Cardio"],
    description: "Balancier explosif de la kettlebell propulsé par les hanches.",
    steps: [
      "Kettlebell au sol à 30 cm devant toi, pieds largeur d'épaules.",
      "Charnière de hanche, dos plat, attrape la poignée à deux mains.",
      "Bascule la kettlebell entre les jambes puis projette les hanches vers l'avant d'un coup sec.",
      "Laisse la kettlebell monter jusqu'à hauteur de poitrine, puis accompagne-la de nouveau entre les jambes.",
    ],
    cues: "Ce sont les hanches qui projettent, pas les bras. La KB monte au niveau de la poitrine max.",
    met: 9.8,
    tracking: "reps_weight",
  },
  {
    name: "Goblet squat + press",
    category: "force",
    equipment: ["haltere", "kettlebell"],
    muscles: ["Jambes", "Épaules", "Gainage"],
    description: "Squat suivi immédiatement d'un développé au-dessus de la tête (thruster).",
    steps: [
      "Charge tenue à deux mains contre la poitrine.",
      "Descends en squat complet.",
      "Remonte de façon dynamique et profite de l'élan pour pousser la charge au-dessus de la tête.",
      "Ramène la charge à la poitrine et enchaîne.",
    ],
    cues: "La remontée du squat lance la charge : c'est un seul mouvement fluide.",
    met: 7,
    tracking: "reps_weight",
  },
  {
    name: "Développé militaire haltères",
    category: "force",
    equipment: ["haltere"],
    muscles: ["Épaules", "Triceps", "Gainage"],
    description: "Debout, on pousse les haltères au-dessus de la tête.",
    steps: [
      "Debout, un haltère à hauteur d'épaules dans chaque main, paumes vers l'avant.",
      "Serre les fessiers et les abdos pour verrouiller le bassin.",
      "Pousse les haltères à la verticale jusqu'à tendre les bras.",
      "Redescends lentement à hauteur d'épaules.",
    ],
    cues: "Fessiers et abdos serrés, ne cambre pas. Verrouille les coudes en haut.",
    tracking: "reps_weight",
  },
  {
    name: "Rowing haltère penché",
    category: "force",
    equipment: ["haltere"],
    muscles: ["Dos", "Biceps"],
    description: "Buste penché à 45°, on tire les haltères vers les hanches.",
    steps: [
      "Un haltère dans chaque main, genoux légèrement fléchis.",
      "Penche le buste en avant à environ 45°, dos bien plat.",
      "Tire les haltères vers les hanches en menant avec les coudes.",
      "Serre les omoplates en haut, puis redescends lentement.",
    ],
    cues: "Dos plat, tire avec les coudes, serre les omoplates en haut.",
    tracking: "reps_weight",
  },
  {
    name: "Rowing unilatéral avec appui",
    category: "force",
    equipment: ["haltere", "banc"],
    muscles: ["Dos", "Biceps"],
    description: "Un genou et une main sur le banc, tirage d'un haltère.",
    steps: [
      "Pose le genou et la main droite sur le banc, pied gauche au sol.",
      "Haltère dans la main gauche, bras tendu vers le sol.",
      "Tire l'haltère vers la hanche en gardant le coude proche du corps.",
      "Redescends lentement. Fais toutes les répétitions puis change de côté.",
    ],
    cues: "Le coude longe le corps, pas de rotation du buste.",
    tracking: "reps_weight",
  },
  {
    name: "Développé couché haltères",
    category: "force",
    equipment: ["haltere", "banc"],
    muscles: ["Pectoraux", "Triceps", "Épaules"],
    description: "Allongée sur un banc, poussée des haltères vers le plafond.",
    steps: [
      "Allongée sur le banc, pieds bien ancrés au sol, omoplates serrées.",
      "Haltères à hauteur de poitrine, coudes à environ 45° du corps.",
      "Pousse à la verticale jusqu'à presque tendre les bras.",
      "Redescends lentement jusqu'à sentir l'étirement des pectoraux.",
    ],
    cues: "Omoplates serrées dans le banc, descends jusqu'à l'étirement, pieds ancrés au sol.",
    tracking: "reps_weight",
  },
  {
    name: "Pompes",
    category: "force",
    equipment: ["poids_du_corps"],
    muscles: ["Pectoraux", "Triceps", "Gainage"],
    description: "Pompes au sol, sur les genoux ou sur un support si besoin.",
    steps: [
      "Mains au sol un peu plus large que les épaules, corps aligné des talons à la tête.",
      "Descends en pliant les coudes à environ 45° du corps.",
      "Va jusqu'à ce que la poitrine soit proche du sol.",
      "Pousse pour remonter en gardant le corps parfaitement gainé.",
    ],
    cues: "Corps en planche du talon à la tête, coudes à 45°, descends la poitrine, pas le menton.",
    tracking: "reps",
  },
  {
    name: "Pompes surélevées",
    category: "force",
    equipment: ["box", "banc"],
    muscles: ["Pectoraux", "Triceps"],
    description: "Mains sur un banc ou une box : version plus accessible des pompes.",
    steps: [
      "Pose les mains sur un banc, une box ou un rebord stable.",
      "Recule les pieds pour former une ligne droite du talon à la tête.",
      "Descends la poitrine vers le support, coudes à 45°.",
      "Pousse pour remonter. Plus le support est haut, plus c'est facile.",
    ],
    cues: "Plus le support est haut, plus c'est facile. Garde la même ligne de corps.",
    tracking: "reps",
  },
  {
    name: "Tirage élastique",
    category: "force",
    equipment: ["elastique"],
    muscles: ["Dos", "Biceps"],
    description: "Tirage horizontal avec un élastique fixé devant soi.",
    steps: [
      "Fixe l'élastique à hauteur de poitrine et recule jusqu'à le tendre légèrement.",
      "Bras tendus devant toi, épaules basses.",
      "Tire les poignées vers les côtes en serrant les omoplates.",
      "Reviens en 2 secondes, sans relâcher complètement la tension.",
    ],
    cues: "Tire jusqu'aux côtes, épaules basses, 2 secondes pour revenir.",
    met: 4,
    tracking: "reps",
  },
  {
    name: "Tractions assistées",
    category: "force",
    equipment: ["elastique", "trx"],
    muscles: ["Dos", "Biceps"],
    description: "Tractions avec aide d'un élastique ou en tirage horizontal aux sangles.",
    steps: [
      "Accroche un élastique à la barre et pose un genou ou un pied dedans.",
      "Suspends-toi bras tendus, puis commence par abaisser les épaules.",
      "Tire jusqu'à passer le menton au-dessus de la barre.",
      "Redescends lentement, sans te laisser tomber.",
    ],
    cues: "Épaules basses avant de tirer, menton au-dessus de la barre, descente contrôlée.",
    tracking: "reps",
  },
  {
    name: "Élévations latérales",
    category: "force",
    equipment: ["haltere"],
    muscles: ["Épaules"],
    description: "Bras qui montent sur les côtés jusqu'à l'horizontale.",
    steps: [
      "Debout, un haltère léger dans chaque main le long du corps.",
      "Coudes très légèrement fléchis, monte les bras sur les côtés.",
      "Arrête-toi à hauteur d'épaules, pas plus haut.",
      "Redescends lentement, sans élan.",
    ],
    cues: "Charge légère, coudes très légèrement fléchis, pas d'élan.",
    met: 3.5,
    tracking: "reps_weight",
  },
  {
    name: "Step-up lesté",
    category: "force",
    equipment: ["haltere", "box", "step"],
    muscles: ["Quadriceps", "Fessiers"],
    description: "Montée sur une box en poussant uniquement avec la jambe du dessus.",
    steps: [
      "Box à hauteur de genou, un haltère dans chaque main.",
      "Pose un pied entier sur la box.",
      "Monte en poussant uniquement avec cette jambe, sans t'aider du pied resté au sol.",
      "Redescends lentement le même pied. Fais toutes les répétitions puis change.",
    ],
    cues: "Le pied du bas ne pousse pas. Descente lente, box à hauteur de genou.",
    tracking: "reps_weight",
  },
  {
    name: "Montée de banc explosive",
    category: "force",
    equipment: ["box", "step"],
    muscles: ["Quadriceps", "Fessiers", "Cardio"],
    description: "Step-up rapide avec le genou libre qui monte haut.",
    steps: [
      "Face à un banc ou un step, sans charge.",
      "Monte un pied et pousse pour arriver debout sur le banc.",
      "Monte le genou libre haut devant toi, bras qui accompagnent.",
      "Redescends et enchaîne en alternant les jambes.",
    ],
    cues: "Rythme soutenu, bras qui accompagnent, alterne les jambes.",
    met: 7,
    tracking: "reps",
  },
  {
    name: "Bon matin élastique",
    category: "force",
    equipment: ["elastique"],
    muscles: ["Ischio-jambiers", "Lombaires", "Fessiers"],
    description: "Charnière de hanche avec un élastique passé derrière la nuque.",
    steps: [
      "Debout sur l'élastique, passe l'autre extrémité derrière la nuque.",
      "Genoux légèrement fléchis, dos plat.",
      "Pousse les fesses en arrière et penche le buste vers l'avant.",
      "Remonte en serrant les fessiers dès que tu sens l'arrière des cuisses.",
    ],
    cues: "Genoux légèrement fléchis, dos plat, descends jusqu'à sentir l'arrière des cuisses.",
    met: 4,
    tracking: "reps",
  },
  {
    name: "Curl biceps haltères",
    category: "force",
    equipment: ["haltere"],
    muscles: ["Biceps"],
    description: "Flexion des coudes avec haltères.",
    steps: [
      "Debout, un haltère dans chaque main, paumes vers l'avant.",
      "Coudes collés au corps, plie les bras pour monter les haltères vers les épaules.",
      "Redescends lentement jusqu'à tendre presque complètement les bras.",
    ],
    cues: "Coudes collés au corps, pas de balancier du buste, descente contrôlée.",
    met: 3.5,
    tracking: "reps_weight",
  },
  {
    name: "Extension triceps au-dessus de la tête",
    category: "force",
    equipment: ["haltere"],
    muscles: ["Triceps"],
    description: "Un haltère tenu à deux mains derrière la tête, on tend les bras.",
    steps: [
      "Debout, tiens un haltère à deux mains au-dessus de la tête, bras tendus.",
      "Plie les coudes pour descendre l'haltère derrière la nuque.",
      "Garde les coudes serrés et pointés vers l'avant.",
      "Tends les bras pour remonter, sans cambrer le dos.",
    ],
    cues: "Coudes serrés vers l'avant, côtes basses, mouvement lent.",
    met: 3.5,
    tracking: "reps_weight",
  },
  {
    name: "Squat isométrique au mur",
    category: "force",
    equipment: ["aucun"],
    muscles: ["Quadriceps"],
    description: "Chaise contre le mur, cuisses parallèles au sol, on tient.",
    steps: [
      "Dos plaqué contre un mur, pieds avancés d'environ 50 cm.",
      "Glisse le long du mur jusqu'à ce que les genoux soient à 90°.",
      "Cuisses parallèles au sol, bras relâchés ou croisés.",
      "Tiens la position en respirant calmement.",
    ],
    cues: "Dos plaqué au mur, genoux à 90°, respire calmement.",
    met: 4,
    tracking: "time",
  },

  /* ------------------- MOUVEMENT / MÉDECINE BALL / SLAM BALL -------------- */
  {
    name: "Slam ball",
    category: "mouvement",
    equipment: ["slam_ball"],
    muscles: ["Corps entier", "Dos", "Gainage"],
    description: "Balle levée au-dessus de la tête puis claquée au sol de toutes ses forces.",
    steps: [
      "Debout, pieds largeur d'épaules, balle au sol entre les pieds.",
      "Ramasse la balle avec le dos plat et lève-la au-dessus de la tête, bras tendus.",
      "Gaine les abdos et claque la balle au sol devant toi de toutes tes forces.",
      "Ramasse-la et enchaîne. Utilise une slam ball qui ne rebondit pas.",
    ],
    cues: "Extension complète en haut, gaine avant de claquer, accompagne la balle jusqu'au sol.",
    met: 7,
    tracking: "reps_weight",
  },
  {
    name: "Wall ball",
    category: "mouvement",
    equipment: ["medecine_ball"],
    muscles: ["Jambes", "Épaules", "Cardio"],
    description: "Squat complet puis lancer de la balle sur une cible en hauteur.",
    steps: [
      "Face à un mur, à environ 60 cm, balle tenue contre la poitrine.",
      "Descends en squat complet en gardant le buste droit.",
      "Remonte de façon explosive et lance la balle vers une cible à ~2,5 m de haut.",
      "Réceptionne la balle contre la poitrine et enchaîne directement le squat suivant.",
    ],
    cues: "La balle part de la poitrine, la puissance vient des jambes. Réceptionne en amortissant vers le squat suivant.",
    met: 8,
    tracking: "reps_weight",
  },
  {
    name: "Lancer rotatif médecine ball",
    category: "mouvement",
    equipment: ["medecine_ball"],
    muscles: ["Obliques", "Hanches", "Épaules"],
    description: "Rotation explosive du buste et lancer de la balle contre un mur.",
    steps: [
      "Place-toi de profil par rapport au mur, à 1,5 m environ.",
      "Balle tenue à deux mains à hauteur de nombril, côté opposé au mur.",
      "Pivote sur le pied arrière et projette la balle contre le mur en tournant les hanches.",
      "Récupère la balle au rebond et enchaîne. Change de côté à mi-série.",
    ],
    cues: "Le pied arrière pivote, la puissance part des hanches. Reste gainée.",
    met: 6,
    tracking: "reps_weight",
  },
  {
    name: "Lancer médecine ball par-dessus l'épaule",
    category: "mouvement",
    equipment: ["medecine_ball", "slam_ball"],
    muscles: ["Corps entier", "Dos"],
    description: "Balle ramassée au sol et projetée par-dessus l'épaule vers l'arrière.",
    steps: [
      "Balle au sol entre les pieds, pieds largeur d'épaules.",
      "Charnière de hanche, dos plat, attrape la balle à deux mains.",
      "Tends jambes et hanches d'un coup sec en projetant la balle par-dessus une épaule.",
      "Retourne-toi, ramasse la balle et enchaîne en alternant les épaules.",
    ],
    cues: "Charnière de hanche pour ramasser, extension explosive. Alterne les épaules.",
    met: 7,
    tracking: "reps_weight",
  },
  {
    name: "Russian twist médecine ball",
    category: "mouvement",
    equipment: ["medecine_ball"],
    muscles: ["Obliques", "Gainage"],
    description: "Assise, buste incliné, la balle passe d'un côté à l'autre.",
    steps: [
      "Assise au sol, genoux pliés, talons posés ou décollés selon ton niveau.",
      "Incline le buste en arrière à environ 45°, dos bien plat.",
      "Tiens la balle à deux mains devant la poitrine.",
      "Fais tourner le buste pour toucher le sol d'un côté puis de l'autre.",
    ],
    cues: "Dos plat (pas rond), la balle touche le sol de chaque côté, respire.",
    met: 4,
    tracking: "reps_weight",
  },
  {
    name: "Wood chop (bûcheron)",
    category: "mouvement",
    equipment: ["medecine_ball", "elastique", "haltere"],
    muscles: ["Obliques", "Épaules", "Gainage"],
    description: "Mouvement diagonal de la hanche vers l'épaule opposée.",
    steps: [
      "Debout, pieds largeur d'épaules, charge tenue à deux mains près d'une hanche.",
      "Bras quasi tendus, monte la charge en diagonale vers l'épaule opposée.",
      "Laisse les hanches et le buste tourner, le pied arrière pivote.",
      "Redescends lentement sur la même diagonale. Change de côté à mi-série.",
    ],
    cues: "Bras tendus, ce sont les hanches et le buste qui tournent, pas seulement les bras.",
    met: 4.5,
    tracking: "reps_weight",
  },
  {
    name: "Farmer walk",
    category: "mouvement",
    equipment: ["haltere", "kettlebell"],
    muscles: ["Trapèzes", "Avant-bras", "Gainage"],
    description: "Marche lestée avec une charge lourde dans chaque main.",
    steps: [
      "Une charge lourde dans chaque main, ramassée avec le dos plat.",
      "Redresse-toi : épaules basses et en arrière, buste droit.",
      "Marche à pas réguliers sur la distance ou la durée prévue.",
      "Repose les charges en pliant les jambes, pas le dos.",
    ],
    cues: "Épaules basses et en arrière, buste droit, pas réguliers, respiration continue.",
    met: 6,
    tracking: "reps_weight",
  },
  {
    name: "Suitcase carry",
    category: "mouvement",
    equipment: ["kettlebell", "haltere"],
    muscles: ["Obliques", "Gainage"],
    description: "Marche avec une seule charge, d'un côté : le gainage lutte contre l'inclinaison.",
    steps: [
      "Une seule charge, tenue d'un côté comme une valise.",
      "Redresse-toi bien droite : les deux épaules à la même hauteur.",
      "Marche en résistant à l'envie de pencher du côté chargé.",
      "Change de main à mi-parcours.",
    ],
    cues: "Reste parfaitement droite, ne penche pas du côté chargé. Change de main à mi-parcours.",
    met: 5,
    tracking: "reps_weight",
  },
  {
    name: "Waiter walk",
    category: "mouvement",
    equipment: ["kettlebell"],
    muscles: ["Épaules", "Gainage"],
    description: "Marche avec une kettlebell tenue bras tendu au-dessus de la tête.",
    steps: [
      "Monte la kettlebell au-dessus de la tête, bras tendu et verrouillé.",
      "Le bras reste près de l'oreille, côtes basses, abdos serrés.",
      "Regard droit devant, marche à pas mesurés.",
      "Change de bras à mi-parcours.",
    ],
    cues: "Bras verrouillé près de l'oreille, côtes basses, regard devant.",
    met: 4.5,
    tracking: "reps_weight",
  },
  {
    name: "Turkish get-up",
    category: "mouvement",
    equipment: ["kettlebell", "haltere"],
    muscles: ["Corps entier", "Épaules", "Gainage"],
    description: "Se lever du sol jusqu'à debout, charge tendue au-dessus de la tête.",
    steps: [
      "Allongée sur le dos, charge tendue vers le plafond, genou du même côté plié.",
      "Prends appui sur le coude opposé, puis sur la main, pour redresser le buste.",
      "Décolle le bassin, glisse la jambe tendue en arrière et pose le genou au sol.",
      "Redresse le buste, puis lève-toi. Refais le chemin exactement en sens inverse.",
    ],
    cues: "Un pas à la fois, le regard reste sur la charge. Commence sans poids pour apprendre.",
    met: 5,
    tracking: "reps_weight",
  },
  {
    name: "Bear crawl",
    category: "mouvement",
    equipment: ["aucun"],
    muscles: ["Gainage", "Épaules", "Coordination"],
    description: "Déplacement à quatre pattes, genoux décollés de quelques centimètres.",
    steps: [
      "À quatre pattes, mains sous les épaules, genoux sous les hanches.",
      "Décolle les genoux de 3-4 cm du sol et garde-les là.",
      "Avance en déplaçant la main droite et le pied gauche en même temps, puis l'inverse.",
      "Garde le bassin stable, comme si un verre d'eau était posé sur le bas de ton dos.",
    ],
    cues: "Bras et jambe opposés en même temps, bassin qui ne se balance pas, dos plat.",
    met: 7,
    tracking: "time",
  },
  {
    name: "Crab walk",
    category: "mouvement",
    equipment: ["aucun"],
    muscles: ["Triceps", "Fessiers", "Gainage"],
    description: "Déplacement en position de crabe, bassin décollé.",
    steps: [
      "Assise au sol, mains derrière toi, doigts orientés vers les pieds.",
      "Pieds à plat, décolle le bassin jusqu'à l'aligner avec les épaules et les genoux.",
      "Avance ou recule en déplaçant une main et le pied opposé.",
      "Garde le bassin haut pendant tout le déplacement.",
    ],
    cues: "Bassin haut en permanence, doigts orientés vers les pieds.",
    met: 6.5,
    tracking: "time",
  },
  {
    name: "Ours / singe (déplacement bas)",
    category: "mouvement",
    equipment: ["aucun"],
    muscles: ["Hanches", "Gainage"],
    description: "Déplacements latéraux en position accroupie, mains au sol.",
    steps: [
      "Accroupis-toi le plus bas possible, mains posées au sol devant toi.",
      "Déplace les deux mains d'un côté, puis fais suivre les pieds.",
      "Reste basse pendant tout le déplacement, ne te relève pas.",
      "Fais quelques mètres dans un sens, puis dans l'autre.",
    ],
    cues: "Reste basse, talons au sol si possible, déplacement fluide.",
    met: 6.5,
    tracking: "time",
  },
  {
    name: "Sit-out",
    category: "mouvement",
    equipment: ["tapis"],
    muscles: ["Obliques", "Gainage", "Épaules"],
    description: "Depuis la planche, une jambe passe sous le corps et le bassin s'ouvre.",
    steps: [
      "Départ en position de planche sur les mains.",
      "Décolle une main et fais passer la jambe opposée sous le corps.",
      "Ouvre le bassin vers le ciel en t'appuyant sur la main restée au sol.",
      "Reviens en planche et alterne les côtés.",
    ],
    cues: "Regarde la jambe qui passe, appuie fort sur la main opposée.",
    met: 6,
    tracking: "reps",
  },
  {
    name: "Clean haltère",
    category: "mouvement",
    equipment: ["haltere", "kettlebell"],
    muscles: ["Corps entier", "Explosivité"],
    description: "Charge amenée du sol à l'épaule en un mouvement explosif.",
    steps: [
      "Charge au sol entre les pieds, charnière de hanche, dos plat.",
      "Tire la charge en tendant jambes et hanches d'un coup sec.",
      "Quand elle est haute, passe rapidement le coude dessous.",
      "Réceptionne la charge sur l'épaule, genoux légèrement fléchis, puis repose-la.",
    ],
    cues: "Extension jambes-hanches d'abord, les coudes passent vite dessous. Charge modérée.",
    met: 6.5,
    tracking: "reps_weight",
  },
  {
    name: "Snatch haltère",
    category: "mouvement",
    equipment: ["haltere", "kettlebell"],
    muscles: ["Corps entier", "Épaules", "Explosivité"],
    description: "Charge amenée du sol à bout de bras au-dessus de la tête en un temps.",
    steps: [
      "Charge au sol entre les pieds, une main dessus, dos plat.",
      "Tends jambes et hanches de façon explosive en gardant la charge près du corps.",
      "Continue le mouvement jusqu'à verrouiller le bras au-dessus de la tête.",
      "Redescends la charge le long du corps et enchaîne. Change de bras à mi-série.",
    ],
    cues: "Trajet proche du corps, extension explosive, verrouille le bras en haut.",
    met: 7,
    tracking: "reps_weight",
  },
  {
    name: "Balayage médecine ball (halo)",
    category: "mouvement",
    equipment: ["medecine_ball", "kettlebell"],
    muscles: ["Épaules", "Gainage"],
    description: "La balle fait le tour de la tête, lentement et près du crâne.",
    steps: [
      "Debout, pieds largeur de bassin, balle tenue à deux mains devant la poitrine.",
      "Fais passer la balle autour de la tête, au plus près du crâne.",
      "Le bassin ne bouge pas du tout : seuls les bras travaillent.",
      "Fais le nombre de tours prévu, puis autant dans l'autre sens.",
    ],
    cues: "Bassin totalement immobile, alterne les sens.",
    met: 4,
    tracking: "reps_weight",
  },
  {
    name: "Fente + rotation médecine ball",
    category: "mouvement",
    equipment: ["medecine_ball"],
    muscles: ["Jambes", "Obliques"],
    description: "Fente avant suivie d'une rotation du buste vers la jambe avant.",
    steps: [
      "Balle tenue à deux mains, bras tendus devant la poitrine.",
      "Fais un grand pas en avant et descends en fente.",
      "En bas, fais tourner le buste vers le côté de la jambe avant.",
      "Reviens face à toi, puis remonte et change de jambe.",
    ],
    cues: "Bras tendus devant, la rotation vient du buste, genou avant stable.",
    met: 5,
    tracking: "reps_weight",
  },
  {
    name: "Deadbug médecine ball",
    category: "mouvement",
    equipment: ["medecine_ball"],
    muscles: ["Abdos profonds", "Gainage"],
    description: "Allongée, la balle est écrasée entre les genoux et les mains, bras/jambes opposés se déploient.",
    steps: [
      "Allongée sur le dos, genoux à 90°, balle coincée entre les genoux et les mains.",
      "Plaque le bas du dos au sol : il ne doit jamais décoller.",
      "Tends lentement un bras derrière la tête et la jambe opposée vers le sol.",
      "Reviens au centre en expirant, puis alterne.",
    ],
    cues: "Bas du dos plaqué au sol en permanence, expire quand tu tends.",
    met: 3.5,
    tracking: "reps",
  },
  {
    name: "Ramassé-porté sac lesté",
    category: "mouvement",
    equipment: ["sac_leste"],
    muscles: ["Corps entier", "Dos", "Gainage"],
    description: "Ramasser un sac au sol, le porter, le reposer proprement.",
    steps: [
      "Sac au sol devant toi, pieds de part et d'autre.",
      "Charnière de hanche, dos plat, attrape le sac à pleines mains.",
      "Redresse-toi en serrant le sac contre la poitrine, puis marche.",
      "Repose-le en pliant les jambes, dos toujours plat.",
    ],
    cues: "Charnière de hanche pour ramasser, dos plat, le sac reste proche du corps.",
    met: 6,
    tracking: "reps_weight",
  },

  /* ------------------------------- À DEUX --------------------------------- */
  {
    name: "Passes médecine ball face à face",
    category: "duo",
    equipment: ["medecine_ball", "partenaire"],
    muscles: ["Épaules", "Gainage", "Réactivité"],
    description: "Les deux partenaires se lancent la balle en poussée poitrine.",
    steps: [
      "Placez-vous face à face à 2-3 mètres, genoux légèrement fléchis.",
      "Tiens la balle à deux mains contre la poitrine.",
      "Pousse la balle vers ton partenaire en tendant les bras d'un coup sec.",
      "Réceptionne en amortissant vers la poitrine, puis renvoie immédiatement.",
    ],
    cues: "Amortis avant de renvoyer, jambes fléchies, distance 2-3 m.",
    met: 4.5,
    tracking: "reps",
  },
  {
    name: "Passes rotatives à deux",
    category: "duo",
    equipment: ["medecine_ball", "partenaire"],
    muscles: ["Obliques", "Hanches"],
    description: "Dos à dos, la balle tourne d'un partenaire à l'autre.",
    steps: [
      "Placez-vous dos à dos, à 30 cm l'un de l'autre, pieds fixes.",
      "L'un tient la balle et fait tourner le buste pour la passer sur le côté.",
      "L'autre la récupère, continue la rotation et la rend de l'autre côté.",
      "La balle tourne ainsi en boucle. Changez de sens à mi-série.",
    ],
    cues: "Pieds fixes, rotation du buste seulement. Change de sens à mi-série.",
    met: 4,
    tracking: "reps",
  },
  {
    name: "Squat + passe",
    category: "duo",
    equipment: ["medecine_ball", "partenaire"],
    muscles: ["Jambes", "Épaules", "Cardio"],
    description: "Chacun fait un squat, puis se passe la balle en se relevant.",
    steps: [
      "Face à face à 2-3 mètres, l'un des deux a la balle.",
      "Descendez tous les deux en squat complet en même temps.",
      "En remontant, celui qui a la balle la lance à l'autre.",
      "Enchaînez : le squat se fait toujours avant la passe.",
    ],
    cues: "Squat complet avant chaque passe. Rythme régulier, on ne se précipite pas.",
    met: 6,
    tracking: "reps",
  },
  {
    name: "Sit-up avec passe",
    category: "duo",
    equipment: ["medecine_ball", "partenaire"],
    muscles: ["Abdos", "Obliques"],
    description: "Face à face pieds contre pieds, la balle passe à chaque relevé.",
    steps: [
      "Allongez-vous face à face, genoux pliés, plantes de pieds l'une contre l'autre.",
      "L'un tient la balle sur la poitrine et remonte en déroulant le dos.",
      "En haut, il lance la balle à l'autre qui est redescendu.",
      "Alternez : quand l'un monte, l'autre descend.",
    ],
    cues: "Déroule le dos, la balle part quand le buste est en haut.",
    met: 5,
    tracking: "reps",
  },
  {
    name: "Planche tape-mains",
    category: "duo",
    equipment: ["partenaire", "tapis"],
    muscles: ["Gainage", "Épaules"],
    description: "En planche face à face, chacun tape la main opposée de l'autre.",
    steps: [
      "Mettez-vous en planche sur les mains, face à face, à une longueur de bras.",
      "Écartez un peu les pieds pour être plus stables.",
      "Décolle une main et viens taper la main opposée de ton partenaire.",
      "Repose, change de main et alternez.",
    ],
    cues: "Bassin qui ne tourne pas, pieds un peu écartés pour la stabilité.",
    met: 4.5,
    tracking: "reps",
  },
  {
    name: "Brouette",
    category: "duo",
    equipment: ["partenaire"],
    muscles: ["Épaules", "Gainage"],
    description: "Un partenaire tient les chevilles, l'autre avance sur les mains.",
    steps: [
      "L'un se met en planche sur les mains, l'autre lui attrape les chevilles.",
      "Celui du sol serre les abdos pour que le dos ne creuse pas.",
      "Il avance sur les mains, le partenaire suit à son rythme.",
      "Faites une courte distance, puis inversez les rôles.",
    ],
    cues: "Gainage serré, ne creuse pas le bas du dos. Distance courte pour commencer.",
    met: 6,
    tracking: "time",
  },
  {
    name: "Course résistée à l'élastique",
    category: "duo",
    equipment: ["elastique", "partenaire"],
    muscles: ["Jambes", "Explosivité"],
    description: "Un partenaire retient à l'élastique pendant que l'autre pousse en avant.",
    steps: [
      "Passe l'élastique autour de ta taille, le partenaire tient l'autre extrémité derrière toi.",
      "Penche le buste vers l'avant et pousse fort dans le sol.",
      "Avance sur 10-15 mètres pendant que le partenaire freine.",
      "Reviens en marchant, puis inversez les rôles.",
    ],
    cues: "Buste incliné vers l'avant, appuis puissants, 10-15 m par répétition.",
    met: 9,
    tracking: "reps",
  },
  {
    name: "Tirage élastique à deux",
    category: "duo",
    equipment: ["elastique", "partenaire"],
    muscles: ["Dos", "Gainage"],
    description: "Face à face, chacun tire l'élastique à tour de rôle ou en même temps.",
    steps: [
      "Face à face, chacun tient une extrémité de l'élastique, bras tendus.",
      "Reculez jusqu'à ce que l'élastique soit légèrement tendu.",
      "Tirez tous les deux en même temps vers vos côtes, en serrant les omoplates.",
      "Revenez en 2 secondes, en gardant la tension.",
    ],
    cues: "Position stable, épaules basses, tempo commun de 2 secondes.",
    met: 4.5,
    tracking: "reps",
  },
  {
    name: "Pompes avec check",
    category: "duo",
    equipment: ["partenaire", "tapis"],
    muscles: ["Pectoraux", "Gainage"],
    description: "Pompes face à face, on tape la main de l'autre en haut.",
    steps: [
      "Placez-vous en position de pompe, face à face, têtes à une longueur de bras.",
      "Descendez tous les deux en même temps.",
      "En haut, bras tendus, tapez-vous dans la main.",
      "Reposez la main et enchaînez la pompe suivante.",
    ],
    cues: "Le check se fait bras tendus, corps toujours gainé.",
    met: 5,
    tracking: "reps",
  },
  {
    name: "Squat isométrique dos à dos",
    category: "duo",
    equipment: ["partenaire"],
    muscles: ["Quadriceps", "Gainage"],
    description: "Dos contre dos, on descend en chaise et on tient ensemble.",
    steps: [
      "Placez-vous dos à dos, en vous appuyant fermement l'un sur l'autre.",
      "Avancez les pieds en glissant le dos vers le bas.",
      "Descendez jusqu'à avoir les genoux à 90°.",
      "Tenez la position en vous parlant pour vous encourager.",
    ],
    cues: "Appui mutuel constant, genoux à 90°, on communique pour tenir.",
    met: 4.5,
    tracking: "time",
  },
  {
    name: "Relais navette à deux",
    category: "duo",
    equipment: ["partenaire"],
    muscles: ["Cardio", "Jambes"],
    description: "L'un court, l'autre gaine ou tient une position : on alterne.",
    steps: [
      "Définissez une distance d'aller-retour et une position à tenir (planche, chaise…).",
      "L'un part en course pendant que l'autre tient la position.",
      "Au retour, tapez-vous dans la main pour échanger les rôles.",
      "Enchaînez jusqu'à la fin du temps prévu.",
    ],
    cues: "L'échange se fait par un check. Tenue de position propre pendant l'attente.",
    met: 8,
    tracking: "time",
  },
  {
    name: "Fentes face à face avec passe",
    category: "duo",
    equipment: ["medecine_ball", "partenaire"],
    muscles: ["Jambes", "Coordination"],
    description: "Chacun descend en fente puis se passe la balle en bas.",
    steps: [
      "Face à face à 2 mètres, l'un des deux a la balle.",
      "Descendez en fente en même temps, genou arrière proche du sol.",
      "En position basse, passez-vous la balle.",
      "Remontez, changez de jambe et recommencez.",
    ],
    cues: "Synchronisez la descente. Genou arrière proche du sol.",
    met: 5.5,
    tracking: "reps",
  },
  {
    name: "Résistance manuelle sur élévations",
    category: "duo",
    equipment: ["partenaire"],
    muscles: ["Épaules", "Bras"],
    description: "Le partenaire freine le mouvement avec les mains, montée et descente.",
    steps: [
      "L'une lève les bras sur les côtés, l'autre pose les mains sur ses poignets.",
      "Le partenaire freine régulièrement pendant la montée (3 secondes).",
      "Il freine aussi la descente (3 secondes).",
      "Parlez-vous : c'est celle qui travaille qui dit si c'est trop ou pas assez.",
    ],
    cues: "Résistance régulière, 3 secondes à la montée, 3 à la descente. On se parle.",
    met: 4,
    tracking: "reps",
  },
  {
    name: "Burpees en miroir",
    category: "duo",
    equipment: ["partenaire"],
    muscles: ["Corps entier", "Cardio"],
    description: "Burpees synchronisés face à face, on tape dans les mains en haut.",
    steps: [
      "Face à face, à une longueur de bras.",
      "Descendez au sol, planche, puis remontez en même temps.",
      "Sautez et tapez-vous dans les mains en haut.",
      "Si l'une fatigue, ralentissez ensemble plutôt que de perdre la synchro.",
    ],
    cues: "Même rythme pour les deux, on ralentit ensemble plutôt que de casser la synchro.",
    met: 8,
    tracking: "reps",
  },
  {
    name: "Planche + saut du partenaire",
    category: "duo",
    equipment: ["partenaire", "tapis"],
    muscles: ["Gainage", "Explosivité"],
    description: "L'un tient la planche, l'autre saute par-dessus à pieds joints, puis on inverse.",
    steps: [
      "L'une se met en planche sur les avant-bras, bien gainée.",
      "L'autre se place à côté et saute par-dessus ses jambes, à pieds joints.",
      "Elle saute d'un côté puis de l'autre pendant le temps prévu.",
      "Inversez les rôles.",
    ],
    cues: "Le sauteur regarde où il atterrit, celui qui gaine reste bien serré.",
    met: 6.5,
    tracking: "reps",
  },

  /* -------------------------------- GAINAGE ------------------------------- */
  {
    name: "Planche",
    category: "core",
    equipment: ["tapis"],
    muscles: ["Gainage", "Abdos profonds"],
    description: "Position de gainage sur les avant-bras et les pointes de pieds.",
    steps: [
      "Pose les avant-bras au sol, coudes juste sous les épaules.",
      "Tends les jambes en arrière, en appui sur les pointes de pieds.",
      "Serre les fessiers et rentre le nombril pour aligner talons-bassin-tête.",
      "Tiens la position en respirant normalement.",
    ],
    cues: "Ligne droite talons-tête, fessiers serrés, nombril rentré, respire.",
    tracking: "time",
  },
  {
    name: "Planche latérale",
    category: "core",
    equipment: ["tapis"],
    muscles: ["Obliques", "Gainage"],
    description: "Gainage sur un avant-bras, corps de profil.",
    steps: [
      "Allongée sur le côté, coude posé juste sous l'épaule.",
      "Jambes tendues, pieds superposés ou légèrement décalés.",
      "Décolle le bassin jusqu'à former une ligne droite des pieds à la tête.",
      "Tiens, puis change de côté. Genou du bas au sol si c'est trop dur.",
    ],
    cues: "Hanche haute, coude sous l'épaule, ne descends pas le bassin.",
    tracking: "time",
  },
  {
    name: "Planche dynamique (haut-bas)",
    category: "core",
    equipment: ["tapis"],
    muscles: ["Gainage", "Épaules", "Triceps"],
    description: "Passage de la planche sur les avant-bras à la planche sur les mains.",
    steps: [
      "Départ en planche sur les avant-bras, pieds un peu écartés.",
      "Pose une main au sol, puis l'autre, pour monter en planche bras tendus.",
      "Redescends sur un avant-bras, puis l'autre.",
      "Alterne le bras qui démarre à chaque répétition.",
    ],
    cues: "Bassin le plus stable possible, alterne le bras qui démarre.",
    met: 5,
    tracking: "reps",
  },
  {
    name: "Hollow hold",
    category: "core",
    equipment: ["tapis"],
    muscles: ["Abdos profonds"],
    description: "Allongée sur le dos, bras et jambes décollés en forme de banane.",
    steps: [
      "Allongée sur le dos, plaque le bas du dos au sol.",
      "Décolle les épaules et tends les bras au-dessus de la tête.",
      "Décolle les jambes tendues de quelques centimètres.",
      "Si le bas du dos décolle, remonte un peu les jambes.",
    ],
    cues: "Bas du dos plaqué au sol : si ça décolle, remonte les jambes.",
    tracking: "time",
  },
  {
    name: "Dead bug",
    category: "core",
    equipment: ["tapis"],
    muscles: ["Abdos profonds", "Gainage"],
    description: "Bras et jambe opposés qui se déploient lentement en gardant le dos plaqué.",
    steps: [
      "Allongée sur le dos, bras tendus vers le plafond, genoux à 90°.",
      "Plaque le bas du dos au sol et garde-le là tout le long.",
      "Descends lentement un bras derrière la tête et la jambe opposée vers le sol.",
      "Reviens au centre en expirant, puis fais l'autre côté.",
    ],
    cues: "Expire en tendant, très lent. Qualité avant quantité.",
    tracking: "reps",
  },
  {
    name: "Bird dog",
    category: "core",
    equipment: ["tapis"],
    muscles: ["Lombaires", "Fessiers", "Gainage"],
    description: "À quatre pattes, on tend le bras et la jambe opposés.",
    steps: [
      "À quatre pattes, mains sous les épaules, genoux sous les hanches, dos plat.",
      "Tends un bras devant et la jambe opposée derrière, à l'horizontale.",
      "Tiens 2 secondes sans laisser le bassin basculer.",
      "Reviens et alterne.",
    ],
    cues: "Bassin qui ne bascule pas, pause de 2 s en extension.",
    tracking: "reps",
  },
  {
    name: "Mountain climbers",
    category: "core",
    equipment: ["tapis"],
    muscles: ["Gainage", "Cardio", "Fléchisseurs de hanche"],
    description: "En planche, les genoux viennent alternativement vers la poitrine.",
    steps: [
      "Position de planche sur les mains, épaules au-dessus des poignets.",
      "Ramène un genou vers la poitrine, puis repose-le.",
      "Alterne rapidement, comme si tu courais sur place.",
      "Garde le bassin bas et stable, sans rebondir.",
    ],
    cues: "Bassin bas et stable, épaules au-dessus des mains, rythme soutenu.",
    met: 8,
    tracking: "time",
  },
  {
    name: "Relevés de jambes",
    category: "core",
    equipment: ["tapis"],
    muscles: ["Abdos"],
    description: "Allongée, jambes tendues qui montent et descendent sans toucher le sol.",
    steps: [
      "Allongée sur le dos, mains sous les fessiers si besoin.",
      "Jambes tendues, monte-les jusqu'à la verticale.",
      "Redescends lentement sans laisser les talons toucher le sol.",
      "Si le bas du dos décolle, plie légèrement les genoux.",
    ],
    cues: "Mains sous les fesses si le bas du dos décolle. Descente contrôlée.",
    tracking: "reps",
  },
  {
    name: "Roulette abdos",
    category: "core",
    equipment: ["roue_abdos"],
    muscles: ["Abdos profonds", "Gainage", "Dos"],
    description: "Depuis les genoux, on déroule la roue vers l'avant puis on revient.",
    steps: [
      "À genoux, roue posée au sol sous les épaules, bras tendus.",
      "Rentre le nombril et déroule lentement vers l'avant.",
      "Va uniquement aussi loin que tu peux sans creuser le dos.",
      "Reviens en tirant avec les abdos, pas avec les bras.",
    ],
    cues: "Dos qui ne se creuse jamais. Amplitude courte au début.",
    met: 4.5,
    tracking: "reps",
  },
  {
    name: "Pallof press",
    category: "core",
    equipment: ["elastique"],
    muscles: ["Obliques", "Gainage"],
    description: "Élastique tendu sur le côté, on pousse les bras devant en résistant à la rotation.",
    steps: [
      "Fixe l'élastique à hauteur de poitrine et place-toi de profil, à 1 m.",
      "Tiens la poignée à deux mains contre le sternum.",
      "Pousse les bras devant toi : l'élastique va vouloir te faire tourner.",
      "Résiste, tiens 2 secondes bras tendus, puis reviens. Change de côté.",
    ],
    cues: "Le buste ne tourne pas d'un millimètre. Tiens 2 s bras tendus.",
    tracking: "reps",
  },
  {
    name: "Superman",
    category: "core",
    equipment: ["tapis"],
    muscles: ["Lombaires", "Fessiers"],
    description: "À plat ventre, bras et jambes décollés simultanément.",
    steps: [
      "Allongée sur le ventre, bras tendus devant, jambes tendues.",
      "Décolle en même temps les bras, la poitrine et les jambes.",
      "Cherche à t'allonger vers l'avant et l'arrière plutôt qu'à monter haut.",
      "Regard vers le sol pour garder la nuque neutre.",
    ],
    cues: "Regard vers le sol, allonge-toi plutôt que de cambrer.",
    tracking: "time",
  },
  {
    name: "Gainage avec charge sur le dos",
    category: "core",
    equipment: ["disque", "tapis"],
    muscles: ["Gainage"],
    description: "Planche classique avec un disque posé sur le haut du dos.",
    steps: [
      "Installe-toi en planche parfaite sur les avant-bras.",
      "Ton partenaire pose délicatement un disque sur le haut de ton dos.",
      "Serre encore plus les abdos et les fessiers pour ne pas creuser.",
      "Tiens, puis fais retirer le disque avant de te relever.",
    ],
    cues: "Charge posée par le partenaire. Position parfaite avant d'ajouter du poids.",
    tracking: "time",
  },

  /* -------------------------------- CARDIO -------------------------------- */
  {
    name: "Rameur — intervalles",
    category: "cardio",
    equipment: ["rameur"],
    muscles: ["Corps entier", "Cardio"],
    description: "Séries de rame intense entrecoupées de récupération active.",
    steps: [
      "Échauffe-toi 3 minutes à allure facile.",
      "Rame fort pendant l'intervalle prévu (par exemple 30 s à 1 min).",
      "Récupère en ramant très lentement le même temps environ.",
      "Répète le nombre de séries prévu et note ta distance.",
    ],
    cues: "Garde une cadence stable, pousse fort avec les jambes. Note ta distance.",
    met: 9.5,
    tracking: "time_distance",
  },
  {
    name: "Vélo — intervalles",
    category: "cardio",
    equipment: ["velo"],
    muscles: ["Jambes", "Cardio"],
    description: "Alternance sprint / récupération sur vélo.",
    steps: [
      "Pédale 3 minutes tranquillement pour t'échauffer.",
      "Monte la résistance et pédale à fond pendant l'intervalle prévu.",
      "Redescends la résistance et pédale très facilement pour récupérer.",
      "Répète le nombre de séries prévu.",
    ],
    cues: "Résistance suffisante pour ne pas pédaler dans le vide. Récup vraiment facile.",
    tracking: "time_distance",
  },
  {
    name: "Burpees",
    category: "cardio",
    equipment: ["aucun"],
    muscles: ["Corps entier", "Cardio"],
    description: "Descente au sol, planche, remontée, saut.",
    steps: [
      "Debout, accroupis-toi et pose les mains au sol.",
      "Envoie les pieds en arrière pour arriver en planche (poitrine au sol si tu veux la version complète).",
      "Ramène les pieds vers les mains d'un coup.",
      "Redresse-toi et termine par un saut, mains au-dessus de la tête.",
    ],
    cues: "Trouve ton rythme et tiens-le. Version sans saut si besoin.",
    met: 8,
    tracking: "reps",
  },
  {
    name: "Battle rope",
    category: "cardio",
    equipment: ["corde_ondulatoire"],
    muscles: ["Épaules", "Bras", "Cardio"],
    description: "Ondulations rapides des cordes, en alterné ou simultané.",
    steps: [
      "Une corde dans chaque main, recule jusqu'à ce qu'elles soient presque tendues.",
      "Fléchis les genoux, dos plat, abdos serrés.",
      "Fais monter et descendre les bras rapidement pour créer des vagues.",
      "Alterne les bras, ou fais-les bouger ensemble pour varier.",
    ],
    cues: "Genoux fléchis, gainage serré, l'onde doit aller jusqu'à l'ancrage.",
    met: 8,
    tracking: "time",
  },
  {
    name: "Corde à sauter — intervalles",
    category: "cardio",
    equipment: ["corde_a_sauter"],
    muscles: ["Mollets", "Cardio"],
    description: "Sauts rapides en séries chronométrées.",
    steps: [
      "Saute à un rythme soutenu pendant la durée de l'intervalle.",
      "Reste sur l'avant du pied, sauts bas et rapides.",
      "Repose-toi le temps prévu entre les séries.",
      "Si tu accroches la corde, repars sans attendre.",
    ],
    cues: "Sauts bas et rapides, la corde passe juste sous les pieds.",
    met: 11,
    tracking: "time",
  },
  {
    name: "Navettes (shuttle run)",
    category: "cardio",
    equipment: ["aucun"],
    muscles: ["Jambes", "Cardio"],
    description: "Allers-retours entre deux repères avec changement de direction.",
    steps: [
      "Place deux repères à 10-15 mètres l'un de l'autre.",
      "Sprinte jusqu'au repère opposé.",
      "Freine sur 2-3 appuis, touche le sol, et repars dans l'autre sens.",
      "Enchaîne pendant la durée prévue.",
    ],
    cues: "Freine sur 2-3 appuis, touche le sol au demi-tour, repars fort.",
    met: 9,
    tracking: "time",
  },
  {
    name: "Sprint sur place",
    category: "cardio",
    equipment: ["aucun"],
    muscles: ["Jambes", "Cardio"],
    description: "Course sur place à intensité maximale sur un temps court.",
    steps: [
      "Debout, buste légèrement penché en avant.",
      "Cours sur place à fréquence maximale, sur l'avant des pieds.",
      "Bras très actifs, comme pour un vrai sprint.",
      "15 à 30 secondes maximum par série, puis récupère.",
    ],
    cues: "Fréquence maximale, bras actifs. 15-30 s max par série.",
    met: 10,
    tracking: "time",
  },
  {
    name: "Marche en côte / tapis incliné",
    category: "cardio",
    equipment: ["aucun"],
    muscles: ["Fessiers", "Cardio"],
    description: "Marche rapide en pente, sans se tenir aux poignées.",
    steps: [
      "Règle l'inclinaison entre 8 et 15 %, ou trouve une vraie côte.",
      "Marche à bonne allure, buste droit, sans te tenir aux poignées.",
      "Fais de grandes foulées pour engager les fessiers.",
      "Maintiens la durée prévue en respirant régulièrement.",
    ],
    cues: "Buste droit, grandes foulées, respiration nasale si possible.",
    met: 6,
    tracking: "time_distance",
  },
  {
    name: "Circuit métabolique",
    category: "cardio",
    equipment: ["aucun"],
    muscles: ["Corps entier", "Cardio"],
    description: "Enchaînement de plusieurs mouvements sans repos, en boucle.",
    steps: [
      "Choisis 3 à 5 mouvements et un nombre de répétitions pour chacun.",
      "Enchaîne-les sans pause entre eux.",
      "À la fin du dernier, repars au premier.",
      "Choisis un rythme que tu peux tenir jusqu'au dernier tour.",
    ],
    cues: "Choisis un rythme que tu peux tenir sur tous les tours.",
    met: 7.5,
    tracking: "time",
  },
  {
    name: "Kettlebell swing — format cardio",
    category: "cardio",
    equipment: ["kettlebell"],
    muscles: ["Fessiers", "Cardio"],
    description: "Swings en séries longues type EMOM ou Tabata.",
    steps: [
      "Même technique que le swing classique : la puissance vient des hanches.",
      "Fais le nombre de répétitions prévu au début de chaque minute.",
      "Récupère le temps restant de la minute.",
      "Repars à la minute suivante, en gardant la même qualité de mouvement.",
    ],
    cues: "Respiration synchronisée : expire en haut. Ne perds pas la technique avec la fatigue.",
    met: 9.8,
    tracking: "reps_weight",
  },

  /* ----------------------------- EXPLOSIVITÉ ------------------------------ */
  {
    name: "Box jump",
    category: "plyo",
    equipment: ["box"],
    muscles: ["Quadriceps", "Fessiers", "Explosivité"],
    description: "Saut à pieds joints sur une box.",
    steps: [
      "Place-toi à 20-30 cm de la box, pieds largeur de bassin.",
      "Fléchis les genoux et arme les bras en arrière.",
      "Saute et atterris à pieds joints au milieu de la box, genoux souples.",
      "Redescends en marchant, jamais en sautant.",
    ],
    cues: "Réception souple au milieu de la box, redescends en marchant, jamais en sautant.",
    tracking: "reps",
  },
  {
    name: "Squat sauté",
    category: "plyo",
    equipment: ["aucun"],
    muscles: ["Quadriceps", "Fessiers"],
    description: "Squat suivi d'un saut vertical maximal.",
    steps: [
      "Pieds largeur d'épaules, descends en squat.",
      "Remonte de façon explosive et saute le plus haut possible.",
      "Réceptionne sur l'avant des pieds puis déroule vers les talons.",
      "Enchaîne directement sur le squat suivant, en silence.",
    ],
    cues: "Réception silencieuse, enchaîne directement sur le squat suivant.",
    tracking: "reps",
  },
  {
    name: "Saut en longueur (broad jump)",
    category: "plyo",
    equipment: ["aucun"],
    muscles: ["Fessiers", "Ischio-jambiers", "Explosivité"],
    description: "Saut horizontal maximal à pieds joints.",
    steps: [
      "Debout, pieds largeur de bassin, bras le long du corps.",
      "Fléchis les genoux en armant les bras vers l'arrière.",
      "Projette-toi vers l'avant en lançant les bras.",
      "Réceptionne à pieds joints, genoux fléchis pour amortir.",
    ],
    cues: "Balancier des bras, projection vers l'avant, réception genoux fléchis.",
    tracking: "reps",
  },
  {
    name: "Skater jumps",
    category: "plyo",
    equipment: ["aucun"],
    muscles: ["Fessiers", "Moyen fessier", "Équilibre"],
    description: "Bonds latéraux d'un pied sur l'autre, comme un patineur.",
    steps: [
      "En appui sur une jambe, l'autre pied décollé derrière.",
      "Bondis sur le côté pour atterrir sur l'autre jambe.",
      "Stabilise-toi 1 seconde, genou dans l'axe du pied.",
      "Rebondis dans l'autre sens et alterne.",
    ],
    cues: "Stabilise 1 s à chaque réception, genou dans l'axe du pied.",
    tracking: "reps",
  },
  {
    name: "Fentes sautées",
    category: "plyo",
    equipment: ["aucun"],
    muscles: ["Quadriceps", "Fessiers"],
    description: "Changement de jambe en l'air depuis la position de fente.",
    steps: [
      "Départ en position de fente, genou arrière proche du sol.",
      "Saute à la verticale et change de jambe en l'air.",
      "Atterris directement en fente sur l'autre jambe, en amortissant.",
      "Enchaîne sans marquer d'arrêt.",
    ],
    cues: "Amorti en descendant, buste droit, ne cogne pas le genou au sol.",
    tracking: "reps",
  },
  {
    name: "Step-up sauté",
    category: "plyo",
    equipment: ["box", "step"],
    muscles: ["Quadriceps", "Fessiers"],
    description: "Montée explosive sur la box avec changement de pied en l'air.",
    steps: [
      "Un pied posé sur une box basse, l'autre au sol.",
      "Pousse fort avec le pied du dessus pour décoller.",
      "Change de pied en l'air et atterris en inversant les appuis.",
      "Enchaîne à rythme régulier en regardant la box.",
    ],
    cues: "Box basse, rythme régulier, regarde la box.",
    tracking: "reps",
  },
  {
    name: "Tuck jumps",
    category: "plyo",
    equipment: ["aucun"],
    muscles: ["Abdos", "Jambes"],
    description: "Saut vertical avec les genoux ramenés vers la poitrine.",
    steps: [
      "Debout, pieds largeur de bassin, mains à hauteur de poitrine.",
      "Saute à la verticale en ramenant les genoux vers les mains.",
      "Tends les jambes juste avant de toucher le sol.",
      "Amortis la réception et enchaîne. Séries courtes : 5 à 8 répétitions.",
    ],
    cues: "Séries courtes (5-8 reps), qualité de réception avant tout.",
    tracking: "reps",
  },
  {
    name: "Pompes claquées",
    category: "plyo",
    equipment: ["tapis"],
    muscles: ["Pectoraux", "Explosivité"],
    description: "Pompe explosive, les mains décollent du sol.",
    steps: [
      "Position de pompe (au sol, sur les genoux, ou mains surélevées).",
      "Descends normalement.",
      "Pousse assez fort pour que les mains décollent du sol.",
      "Repose les mains en pliant immédiatement les coudes pour amortir.",
    ],
    cues: "Version genoux ou surélevée au début. Amortis à la réception.",
    met: 6,
    tracking: "reps",
  },

  /* ------------------------------- MOBILITÉ ------------------------------- */
  {
    name: "World's greatest stretch",
    category: "mobilite",
    equipment: ["tapis"],
    muscles: ["Hanches", "Dos", "Ischio-jambiers"],
    description: "Fente profonde, coude au sol, puis rotation du buste vers le ciel.",
    steps: [
      "Fais un grand pas en avant et descends en fente profonde.",
      "Pose la main intérieure au sol et amène le coude vers le sol, à côté du pied avant.",
      "Puis fais tourner le buste en levant le bras intérieur vers le plafond.",
      "Suis la main du regard, respire 3 fois, puis change de côté.",
    ],
    cues: "Respire dans la position, 3 respirations par côté.",
    met: 3,
    tracking: "reps",
  },
  {
    name: "90/90 hanches",
    category: "mobilite",
    equipment: ["tapis"],
    muscles: ["Hanches"],
    description: "Assise, jambes à 90° devant et sur le côté, on bascule d'un côté à l'autre.",
    steps: [
      "Assise au sol, une jambe pliée à 90° devant toi, l'autre à 90° sur le côté.",
      "Dos droit, mains posées au sol pour t'aider.",
      "Fais basculer les deux genoux de l'autre côté pour inverser la position.",
      "Alterne lentement, sans forcer sur les genoux.",
    ],
    cues: "Dos droit, mouvement lent, ne force pas sur les genoux.",
    tracking: "reps",
  },
  {
    name: "Chat-vache",
    category: "mobilite",
    equipment: ["tapis"],
    muscles: ["Colonne vertébrale"],
    description: "À quatre pattes, alternance dos rond / dos creux.",
    steps: [
      "À quatre pattes, mains sous les épaules, genoux sous les hanches.",
      "Inspire en creusant le dos et en levant le regard.",
      "Expire en arrondissant le dos et en rentrant le menton.",
      "Enchaîne lentement au rythme de ta respiration.",
    ],
    cues: "Synchronise avec la respiration : inspire en creusant, expire en arrondissant.",
    tracking: "reps",
  },
  {
    name: "Ouverture thoracique",
    category: "mobilite",
    equipment: ["tapis"],
    muscles: ["Dos", "Pectoraux"],
    description: "Allongée sur le côté, le bras du dessus s'ouvre vers l'arrière.",
    steps: [
      "Allongée sur le côté, genoux pliés à 90°, bras tendus devant toi l'un sur l'autre.",
      "Garde les genoux collés au sol.",
      "Ouvre le bras du dessus vers l'arrière, en suivant la main du regard.",
      "Va jusqu'où c'est confortable, respire, puis reviens. Change de côté.",
    ],
    cues: "Genoux qui restent collés au sol, suis la main du regard.",
    tracking: "reps",
  },
  {
    name: "Étirement psoas",
    category: "mobilite",
    equipment: ["tapis"],
    muscles: ["Psoas", "Quadriceps"],
    description: "Fente genou au sol, bassin poussé vers l'avant.",
    steps: [
      "Position de fente, genou arrière posé au sol (sur un coussin si besoin).",
      "Serre le fessier de la jambe arrière pour basculer le bassin.",
      "Pousse doucement le bassin vers l'avant.",
      "Tiens en respirant, puis change de côté.",
    ],
    cues: "Rétroversion du bassin (fessier serré) pour vraiment sentir l'avant de la hanche.",
    tracking: "time",
  },
  {
    name: "Étirement ischio-jambiers",
    category: "mobilite",
    equipment: ["tapis"],
    muscles: ["Ischio-jambiers"],
    description: "Jambe tendue devant, on pousse les fesses vers l'arrière.",
    steps: [
      "Une jambe tendue devant toi, talon au sol, pointe de pied vers le haut.",
      "L'autre jambe fléchie, mains posées sur la cuisse.",
      "Pousse les fesses vers l'arrière en gardant le dos plat.",
      "Tiens en respirant, puis change de jambe.",
    ],
    cues: "Dos plat, la sensation doit être dans le muscle, jamais derrière le genou.",
    tracking: "time",
  },
  {
    name: "Pigeon",
    category: "mobilite",
    equipment: ["tapis"],
    muscles: ["Fessiers", "Hanches"],
    description: "Jambe avant repliée, jambe arrière tendue, buste qui descend.",
    steps: [
      "Depuis la position à quatre pattes, ramène un genou vers la main du même côté.",
      "Pose le tibia devant toi, plus ou moins parallèle au bord du tapis.",
      "Tends la jambe arrière derrière toi, dessus du pied au sol.",
      "Descends le buste vers l'avant, 60 à 90 secondes, puis change de côté.",
    ],
    cues: "Coussin sous la fesse si c'est trop intense. 60-90 s par côté.",
    tracking: "time",
  },
  {
    name: "Squat profond tenu",
    category: "mobilite",
    equipment: ["aucun"],
    muscles: ["Hanches", "Chevilles"],
    description: "Position accroupie basse tenue, coudes qui écartent les genoux.",
    steps: [
      "Pieds largeur d'épaules, descends le plus bas possible en squat.",
      "Mains jointes devant la poitrine, coudes à l'intérieur des genoux.",
      "Pousse doucement les genoux vers l'extérieur avec les coudes.",
      "Si les talons décollent, pose-les sur un petit rehaussement.",
    ],
    cues: "Talons au sol si possible, sinon surélève-les. Respire profondément.",
    met: 2.8,
    tracking: "time",
  },
  {
    name: "Étirement épaules au mur",
    category: "mobilite",
    equipment: ["aucun"],
    muscles: ["Épaules", "Pectoraux"],
    description: "Main au mur, on fait pivoter le buste dans le sens opposé.",
    steps: [
      "Pose la paume à plat sur un mur, bras tendu à hauteur d'épaule.",
      "Fais pivoter lentement le buste dans le sens opposé au bras.",
      "Va jusqu'à sentir l'étirement à l'avant de l'épaule et de la poitrine.",
      "Tiens 30 secondes, puis change de côté.",
    ],
    cues: "Bras à hauteur d'épaule, rotation lente, 30 s par côté.",
    tracking: "time",
  },
  {
    name: "Respiration et retour au calme",
    category: "mobilite",
    equipment: ["tapis"],
    muscles: ["Système nerveux"],
    description: "Allongée, respiration lente pour faire redescendre le cardiaque.",
    steps: [
      "Allongée sur le dos, jambes fléchies ou posées sur une chaise.",
      "Une main sur le ventre, ferme les yeux.",
      "Inspire par le nez 4 secondes, bloque 2 secondes, expire 6 secondes.",
      "Continue jusqu'à sentir le rythme cardiaque redescendre.",
    ],
    cues: "Inspire 4 s, bloque 2 s, expire 6 s. Ferme les yeux.",
    tracking: "time",
  },
];
