import type { CategoryKey, EquipmentKey, TrackingKey } from "./constants";

export type SeedExercise = {
  name: string;
  category: CategoryKey;
  equipment: EquipmentKey[];
  muscles: string[];
  description: string;
  cues: string;
  tracking: TrackingKey;
};

/**
 * Bibliothèque de départ : orientée poids libres, médecine ball / slam ball,
 * mouvement fonctionnel et exercices à deux. Peu de muscu isolée.
 * Le coach peut en ajouter autant qu'il veut depuis l'app.
 */
export const EXERCISE_LIBRARY: SeedExercise[] = [
  /* ----------------------------- ÉCHAUFFEMENT ----------------------------- */
  {
    name: "Rameur — échauffement",
    category: "echauffement",
    equipment: ["rameur"],
    muscles: ["Corps entier", "Cardio"],
    description: "Rame à allure facile pour monter en température et mobiliser le dos.",
    cues: "Ordre du mouvement : jambes → buste → bras. Retour : bras → buste → jambes. Cadence 20-24 coups/min.",
    tracking: "time_distance",
  },
  {
    name: "Vélo — échauffement",
    category: "echauffement",
    equipment: ["velo"],
    muscles: ["Jambes", "Cardio"],
    description: "Pédalage progressif, résistance légère, pour lancer la machine.",
    cues: "Commence très facile, monte la résistance toutes les 2 minutes. Tu dois pouvoir parler.",
    tracking: "time_distance",
  },
  {
    name: "Corde à sauter — échauffement",
    category: "echauffement",
    equipment: ["corde_a_sauter"],
    muscles: ["Mollets", "Cardio", "Coordination"],
    description: "Petits sauts légers pour réveiller les chevilles et le système nerveux.",
    cues: "Reste sur l'avant du pied, coudes près du corps, ce sont les poignets qui tournent.",
    tracking: "time",
  },
  {
    name: "Mobilité articulaire complète",
    category: "echauffement",
    equipment: ["aucun"],
    muscles: ["Corps entier"],
    description: "Cercles de chevilles, genoux, hanches, buste, épaules, poignets, cou.",
    cues: "10 rotations par articulation, de bas en haut. Amplitude progressive, jamais forcée.",
    tracking: "time",
  },
  {
    name: "Montées de genoux",
    category: "echauffement",
    equipment: ["aucun"],
    muscles: ["Fléchisseurs de hanche", "Cardio"],
    description: "Course sur place genoux hauts, rythme soutenu.",
    cues: "Genou à hauteur de hanche, buste droit, appuis dynamiques sur l'avant du pied.",
    tracking: "time",
  },
  {
    name: "Talons-fesses",
    category: "echauffement",
    equipment: ["aucun"],
    muscles: ["Ischio-jambiers", "Cardio"],
    description: "Course sur place en ramenant les talons vers les fessiers.",
    cues: "Bassin bien droit, ne cambre pas. Rythme rapide et léger.",
    tracking: "time",
  },
  {
    name: "Pas chassés latéraux",
    category: "echauffement",
    equipment: ["aucun"],
    muscles: ["Fessiers", "Adducteurs"],
    description: "Déplacements latéraux en position semi-fléchie.",
    cues: "Reste bas, ne croise pas les pieds, pousse fort avec la jambe extérieure.",
    tracking: "time",
  },
  {
    name: "Activation fessiers élastique",
    category: "echauffement",
    equipment: ["elastique"],
    muscles: ["Moyen fessier"],
    description: "Pas latéraux (monster walk) avec un élastique au-dessus des genoux.",
    cues: "Genoux qui poussent vers l'extérieur, petits pas, tension permanente dans l'élastique.",
    tracking: "reps",
  },
  {
    name: "Pont fessier au sol",
    category: "echauffement",
    equipment: ["tapis"],
    muscles: ["Fessiers", "Ischio-jambiers"],
    description: "Allongée sur le dos, on décolle le bassin en serrant les fessiers.",
    cues: "Pousse dans les talons, serre les fessiers en haut 1 seconde, ne cambre pas le bas du dos.",
    tracking: "reps",
  },
  {
    name: "Squat au poids du corps",
    category: "echauffement",
    equipment: ["aucun"],
    muscles: ["Quadriceps", "Fessiers"],
    description: "Squat lent et contrôlé pour préparer les hanches et les genoux.",
    cues: "Pieds largeur d'épaules, poitrine haute, descends jusqu'à ce que les cuisses soient parallèles au sol.",
    tracking: "reps",
  },
  {
    name: "Fentes marchées d'échauffement",
    category: "echauffement",
    equipment: ["aucun"],
    muscles: ["Quadriceps", "Fessiers", "Psoas"],
    description: "Fentes avant en avançant, sans charge, amplitude progressive.",
    cues: "Grand pas, genou arrière proche du sol, buste vertical.",
    tracking: "reps",
  },
  {
    name: "Rotations du buste",
    category: "echauffement",
    equipment: ["aucun"],
    muscles: ["Obliques", "Dos"],
    description: "Bassin fixe, on fait tourner le haut du corps de gauche à droite.",
    cues: "Bras relâchés, ce sont les épaules qui emmènent. Bassin qui ne bouge pas.",
    tracking: "reps",
  },
  {
    name: "Cercles de bras",
    category: "echauffement",
    equipment: ["aucun"],
    muscles: ["Épaules"],
    description: "Grands cercles avant puis arrière pour ouvrir les épaules.",
    cues: "Bras tendus, amplitude maximale, 15 dans chaque sens.",
    tracking: "reps",
  },
  {
    name: "Inchworm",
    category: "echauffement",
    equipment: ["tapis"],
    muscles: ["Ischio-jambiers", "Épaules", "Gainage"],
    description: "Debout, mains au sol, on marche en planche puis on revient.",
    cues: "Jambes aussi tendues que possible à l'aller, gainage serré en position de planche.",
    tracking: "reps",
  },

  /* ---------------------------- FORCE / POIDS LIBRES ---------------------- */
  {
    name: "Goblet squat",
    category: "force",
    equipment: ["haltere", "kettlebell"],
    muscles: ["Quadriceps", "Fessiers", "Gainage"],
    description: "Squat avec un haltère ou une kettlebell tenu contre la poitrine.",
    cues: "Coudes à l'intérieur des genoux en bas, poitrine haute, poids dans tout le pied.",
    tracking: "reps_weight",
  },
  {
    name: "Squat sumo haltère",
    category: "force",
    equipment: ["haltere", "kettlebell"],
    muscles: ["Fessiers", "Adducteurs", "Quadriceps"],
    description: "Squat pieds très écartés, pointes vers l'extérieur, haltère entre les jambes.",
    cues: "Genoux dans l'axe des pieds, descends bas, pousse le sol vers l'extérieur.",
    tracking: "reps_weight",
  },
  {
    name: "Squat bulgare",
    category: "force",
    equipment: ["haltere", "banc"],
    muscles: ["Quadriceps", "Fessiers"],
    description: "Fente arrière surélevée, pied arrière posé sur un banc.",
    cues: "Pied avant assez loin du banc, descends verticalement, ne pars pas en avant.",
    tracking: "reps_weight",
  },
  {
    name: "Front squat haltères",
    category: "force",
    equipment: ["haltere"],
    muscles: ["Quadriceps", "Fessiers", "Gainage"],
    description: "Haltères posés sur les épaules, squat complet.",
    cues: "Coudes hauts, buste vertical, respiration bloquée à la descente.",
    tracking: "reps_weight",
  },
  {
    name: "Squat sauté lesté",
    category: "force",
    equipment: ["haltere", "gilet_leste"],
    muscles: ["Quadriceps", "Fessiers", "Explosivité"],
    description: "Squat avec une charge légère, terminé par un saut.",
    cues: "Charge légère uniquement. Réception silencieuse, genoux souples.",
    tracking: "reps_weight",
  },
  {
    name: "Fentes avant haltères",
    category: "force",
    equipment: ["haltere"],
    muscles: ["Quadriceps", "Fessiers"],
    description: "Fentes alternées avec un haltère dans chaque main.",
    cues: "Grand pas, genou arrière qui frôle le sol, pousse sur le talon avant pour remonter.",
    tracking: "reps_weight",
  },
  {
    name: "Fentes arrière haltères",
    category: "force",
    equipment: ["haltere"],
    muscles: ["Fessiers", "Ischio-jambiers"],
    description: "On recule au lieu d'avancer : plus doux pour les genoux, plus fessiers.",
    cues: "Le pied arrière se pose sur la pointe, le buste reste droit.",
    tracking: "reps_weight",
  },
  {
    name: "Fentes marchées lestées",
    category: "force",
    equipment: ["haltere", "sac_leste"],
    muscles: ["Quadriceps", "Fessiers", "Équilibre"],
    description: "Enchaînement de fentes en avançant sur une distance donnée.",
    cues: "Regard loin devant, gainage serré, pas trop rapide.",
    tracking: "reps_weight",
  },
  {
    name: "Fentes latérales",
    category: "force",
    equipment: ["haltere", "kettlebell"],
    muscles: ["Adducteurs", "Fessiers"],
    description: "Grand pas sur le côté, on s'assoit sur la jambe fléchie.",
    cues: "La jambe opposée reste tendue, pied à plat, fesses en arrière.",
    tracking: "reps_weight",
  },
  {
    name: "Soulevé de terre jambes tendues (haltères)",
    category: "force",
    equipment: ["haltere"],
    muscles: ["Ischio-jambiers", "Fessiers", "Lombaires"],
    description: "Charnière de hanche avec haltères, jambes quasi tendues.",
    cues: "Dos plat, fesses vers l'arrière, les haltères frôlent les jambes. Étirement à l'arrière des cuisses.",
    tracking: "reps_weight",
  },
  {
    name: "Soulevé de terre unilatéral",
    category: "force",
    equipment: ["haltere", "kettlebell"],
    muscles: ["Ischio-jambiers", "Fessiers", "Équilibre"],
    description: "Charnière sur une jambe, l'autre part en arrière dans l'alignement.",
    cues: "Hanches carrées (le bassin ne s'ouvre pas), dos plat, mouvement lent.",
    tracking: "reps_weight",
  },
  {
    name: "Hip thrust",
    category: "force",
    equipment: ["haltere", "barre", "banc"],
    muscles: ["Fessiers"],
    description: "Dos appuyé sur un banc, on pousse le bassin vers le plafond.",
    cues: "Menton rentré, côtes basses, serre les fessiers 1 s en haut sans cambrer.",
    tracking: "reps_weight",
  },
  {
    name: "Hip thrust une jambe",
    category: "force",
    equipment: ["banc", "poids_du_corps"],
    muscles: ["Fessiers", "Gainage"],
    description: "Version unilatérale du hip thrust, jambe libre fléchie ou tendue.",
    cues: "Bassin bien horizontal, ne laisse pas une hanche descendre.",
    tracking: "reps_weight",
  },
  {
    name: "Swing kettlebell",
    category: "force",
    equipment: ["kettlebell"],
    muscles: ["Fessiers", "Ischio-jambiers", "Dos", "Cardio"],
    description: "Balancier explosif de la kettlebell propulsé par les hanches.",
    cues: "Ce sont les hanches qui projettent, pas les bras. La KB monte au niveau de la poitrine max.",
    tracking: "reps_weight",
  },
  {
    name: "Goblet squat + press",
    category: "force",
    equipment: ["haltere", "kettlebell"],
    muscles: ["Jambes", "Épaules", "Gainage"],
    description: "Squat suivi immédiatement d'un développé au-dessus de la tête (thruster).",
    cues: "La remontée du squat lance la charge : c'est un seul mouvement fluide.",
    tracking: "reps_weight",
  },
  {
    name: "Développé militaire haltères",
    category: "force",
    equipment: ["haltere"],
    muscles: ["Épaules", "Triceps", "Gainage"],
    description: "Debout, on pousse les haltères au-dessus de la tête.",
    cues: "Fessiers et abdos serrés, ne cambre pas. Verrouille les coudes en haut.",
    tracking: "reps_weight",
  },
  {
    name: "Rowing haltère penché",
    category: "force",
    equipment: ["haltere"],
    muscles: ["Dos", "Biceps"],
    description: "Buste penché à 45°, on tire les haltères vers les hanches.",
    cues: "Dos plat, tire avec les coudes, serre les omoplates en haut.",
    tracking: "reps_weight",
  },
  {
    name: "Rowing unilatéral avec appui",
    category: "force",
    equipment: ["haltere", "banc"],
    muscles: ["Dos", "Biceps"],
    description: "Un genou et une main sur le banc, tirage d'un haltère.",
    cues: "Le coude longe le corps, pas de rotation du buste.",
    tracking: "reps_weight",
  },
  {
    name: "Développé couché haltères",
    category: "force",
    equipment: ["haltere", "banc"],
    muscles: ["Pectoraux", "Triceps", "Épaules"],
    description: "Allongée sur un banc, poussée des haltères vers le plafond.",
    cues: "Omoplates serrées dans le banc, descends jusqu'à l'étirement, pieds ancrés au sol.",
    tracking: "reps_weight",
  },
  {
    name: "Pompes",
    category: "force",
    equipment: ["poids_du_corps"],
    muscles: ["Pectoraux", "Triceps", "Gainage"],
    description: "Pompes au sol, sur les genoux ou sur un support si besoin.",
    cues: "Corps en planche du talon à la tête, coudes à 45°, descends la poitrine, pas le menton.",
    tracking: "reps",
  },
  {
    name: "Pompes surélevées",
    category: "force",
    equipment: ["box", "banc"],
    muscles: ["Pectoraux", "Triceps"],
    description: "Mains sur un banc ou une box : version plus accessible des pompes.",
    cues: "Plus le support est haut, plus c'est facile. Garde la même ligne de corps.",
    tracking: "reps",
  },
  {
    name: "Tirage élastique",
    category: "force",
    equipment: ["elastique"],
    muscles: ["Dos", "Biceps"],
    description: "Tirage horizontal avec un élastique fixé devant soi.",
    cues: "Tire jusqu'aux côtes, épaules basses, 2 secondes pour revenir.",
    tracking: "reps",
  },
  {
    name: "Tractions assistées",
    category: "force",
    equipment: ["elastique", "trx"],
    muscles: ["Dos", "Biceps"],
    description: "Tractions avec aide d'un élastique ou en tirage horizontal aux sangles.",
    cues: "Épaules basses avant de tirer, menton au-dessus de la barre, descente contrôlée.",
    tracking: "reps",
  },
  {
    name: "Élévations latérales",
    category: "force",
    equipment: ["haltere"],
    muscles: ["Épaules"],
    description: "Bras qui montent sur les côtés jusqu'à l'horizontale.",
    cues: "Charge légère, coudes très légèrement fléchis, pas d'élan.",
    tracking: "reps_weight",
  },
  {
    name: "Step-up lesté",
    category: "force",
    equipment: ["haltere", "box", "step"],
    muscles: ["Quadriceps", "Fessiers"],
    description: "Montée sur une box en poussant uniquement avec la jambe du dessus.",
    cues: "Le pied du bas ne pousse pas. Descente lente, box à hauteur de genou.",
    tracking: "reps_weight",
  },
  {
    name: "Montée de banc explosive",
    category: "force",
    equipment: ["box", "step"],
    muscles: ["Quadriceps", "Fessiers", "Cardio"],
    description: "Step-up rapide avec le genou libre qui monte haut.",
    cues: "Rythme soutenu, bras qui accompagnent, alterne les jambes.",
    tracking: "reps",
  },
  {
    name: "Bon matin élastique",
    category: "force",
    equipment: ["elastique"],
    muscles: ["Ischio-jambiers", "Lombaires", "Fessiers"],
    description: "Charnière de hanche avec un élastique passé derrière la nuque.",
    cues: "Genoux légèrement fléchis, dos plat, descends jusqu'à sentir l'arrière des cuisses.",
    tracking: "reps",
  },
  {
    name: "Curl biceps haltères",
    category: "force",
    equipment: ["haltere"],
    muscles: ["Biceps"],
    description: "Flexion des coudes avec haltères.",
    cues: "Coudes collés au corps, pas de balancier du buste, descente contrôlée.",
    tracking: "reps_weight",
  },
  {
    name: "Extension triceps au-dessus de la tête",
    category: "force",
    equipment: ["haltere"],
    muscles: ["Triceps"],
    description: "Un haltère tenu à deux mains derrière la tête, on tend les bras.",
    cues: "Coudes serrés vers l'avant, côtes basses, mouvement lent.",
    tracking: "reps_weight",
  },
  {
    name: "Squat isométrique au mur",
    category: "force",
    equipment: ["aucun"],
    muscles: ["Quadriceps"],
    description: "Chaise contre le mur, cuisses parallèles au sol, on tient.",
    cues: "Dos plaqué au mur, genoux à 90°, respire calmement.",
    tracking: "time",
  },

  /* ------------------- MOUVEMENT / MÉDECINE BALL / SLAM BALL -------------- */
  {
    name: "Slam ball",
    category: "mouvement",
    equipment: ["slam_ball"],
    muscles: ["Corps entier", "Dos", "Gainage"],
    description: "Balle levée au-dessus de la tête puis claquée au sol de toutes ses forces.",
    cues: "Extension complète en haut, gaine avant de claquer, accompagne la balle jusqu'au sol.",
    tracking: "reps_weight",
  },
  {
    name: "Wall ball",
    category: "mouvement",
    equipment: ["medecine_ball"],
    muscles: ["Jambes", "Épaules", "Cardio"],
    description: "Squat complet puis lancer de la balle sur une cible en hauteur.",
    cues: "La balle part de la poitrine, la puissance vient des jambes. Réceptionne en amortissant vers le squat suivant.",
    tracking: "reps_weight",
  },
  {
    name: "Lancer rotatif médecine ball",
    category: "mouvement",
    equipment: ["medecine_ball"],
    muscles: ["Obliques", "Hanches", "Épaules"],
    description: "Rotation explosive du buste et lancer de la balle contre un mur.",
    cues: "Le pied arrière pivote, la puissance part des hanches. Reste gainée.",
    tracking: "reps_weight",
  },
  {
    name: "Lancer médecine ball par-dessus l'épaule",
    category: "mouvement",
    equipment: ["medecine_ball", "slam_ball"],
    muscles: ["Corps entier", "Dos"],
    description: "Balle ramassée au sol et projetée par-dessus l'épaule vers l'arrière.",
    cues: "Charnière de hanche pour ramasser, extension explosive. Alterne les épaules.",
    tracking: "reps_weight",
  },
  {
    name: "Russian twist médecine ball",
    category: "mouvement",
    equipment: ["medecine_ball"],
    muscles: ["Obliques", "Gainage"],
    description: "Assise, buste incliné, la balle passe d'un côté à l'autre.",
    cues: "Dos plat (pas rond), la balle touche le sol de chaque côté, respire.",
    tracking: "reps_weight",
  },
  {
    name: "Wood chop (bûcheron)",
    category: "mouvement",
    equipment: ["medecine_ball", "elastique", "haltere"],
    muscles: ["Obliques", "Épaules", "Gainage"],
    description: "Mouvement diagonal de la hanche vers l'épaule opposée.",
    cues: "Bras tendus, ce sont les hanches et le buste qui tournent, pas seulement les bras.",
    tracking: "reps_weight",
  },
  {
    name: "Farmer walk",
    category: "mouvement",
    equipment: ["haltere", "kettlebell"],
    muscles: ["Trapèzes", "Avant-bras", "Gainage"],
    description: "Marche lestée avec une charge lourde dans chaque main.",
    cues: "Épaules basses et en arrière, buste droit, pas réguliers, respiration continue.",
    tracking: "reps_weight",
  },
  {
    name: "Suitcase carry",
    category: "mouvement",
    equipment: ["kettlebell", "haltere"],
    muscles: ["Obliques", "Gainage"],
    description: "Marche avec une seule charge, d'un côté : le gainage lutte contre l'inclinaison.",
    cues: "Reste parfaitement droite, ne penche pas du côté chargé. Change de main à mi-parcours.",
    tracking: "reps_weight",
  },
  {
    name: "Waiter walk",
    category: "mouvement",
    equipment: ["kettlebell"],
    muscles: ["Épaules", "Gainage"],
    description: "Marche avec une kettlebell tenue bras tendu au-dessus de la tête.",
    cues: "Bras verrouillé près de l'oreille, côtes basses, regard devant.",
    tracking: "reps_weight",
  },
  {
    name: "Turkish get-up",
    category: "mouvement",
    equipment: ["kettlebell", "haltere"],
    muscles: ["Corps entier", "Épaules", "Gainage"],
    description: "Se lever du sol jusqu'à debout, charge tendue au-dessus de la tête.",
    cues: "Un pas à la fois, le regard reste sur la charge. Commence sans poids pour apprendre.",
    tracking: "reps_weight",
  },
  {
    name: "Bear crawl",
    category: "mouvement",
    equipment: ["aucun"],
    muscles: ["Gainage", "Épaules", "Coordination"],
    description: "Déplacement à quatre pattes, genoux décollés de quelques centimètres.",
    cues: "Bras et jambe opposés en même temps, bassin qui ne se balance pas, dos plat.",
    tracking: "time",
  },
  {
    name: "Crab walk",
    category: "mouvement",
    equipment: ["aucun"],
    muscles: ["Triceps", "Fessiers", "Gainage"],
    description: "Déplacement en position de crabe, bassin décollé.",
    cues: "Bassin haut en permanence, doigts orientés vers les pieds.",
    tracking: "time",
  },
  {
    name: "Ours / singe (déplacement bas)",
    category: "mouvement",
    equipment: ["aucun"],
    muscles: ["Hanches", "Gainage"],
    description: "Déplacements latéraux en position accroupie, mains au sol.",
    cues: "Reste basse, talons au sol si possible, déplacement fluide.",
    tracking: "time",
  },
  {
    name: "Sit-out",
    category: "mouvement",
    equipment: ["tapis"],
    muscles: ["Obliques", "Gainage", "Épaules"],
    description: "Depuis la planche, une jambe passe sous le corps et le bassin s'ouvre.",
    cues: "Regarde la jambe qui passe, appuie fort sur la main opposée.",
    tracking: "reps",
  },
  {
    name: "Clean haltère",
    category: "mouvement",
    equipment: ["haltere", "kettlebell"],
    muscles: ["Corps entier", "Explosivité"],
    description: "Charge amenée du sol à l'épaule en un mouvement explosif.",
    cues: "Extension jambes-hanches d'abord, les coudes passent vite dessous. Charge modérée.",
    tracking: "reps_weight",
  },
  {
    name: "Snatch haltère",
    category: "mouvement",
    equipment: ["haltere", "kettlebell"],
    muscles: ["Corps entier", "Épaules", "Explosivité"],
    description: "Charge amenée du sol à bout de bras au-dessus de la tête en un temps.",
    cues: "Trajet proche du corps, extension explosive, verrouille le bras en haut.",
    tracking: "reps_weight",
  },
  {
    name: "Balayage médecine ball (halo)",
    category: "mouvement",
    equipment: ["medecine_ball", "kettlebell"],
    muscles: ["Épaules", "Gainage"],
    description: "La balle fait le tour de la tête, lentement et près du crâne.",
    cues: "Bassin totalement immobile, alterne les sens.",
    tracking: "reps_weight",
  },
  {
    name: "Fente + rotation médecine ball",
    category: "mouvement",
    equipment: ["medecine_ball"],
    muscles: ["Jambes", "Obliques"],
    description: "Fente avant suivie d'une rotation du buste vers la jambe avant.",
    cues: "Bras tendus devant, la rotation vient du buste, genou avant stable.",
    tracking: "reps_weight",
  },
  {
    name: "Deadbug médecine ball",
    category: "mouvement",
    equipment: ["medecine_ball"],
    muscles: ["Abdos profonds", "Gainage"],
    description: "Allongée, la balle est écrasée entre les genoux et les mains, bras/jambes opposés se déploient.",
    cues: "Bas du dos plaqué au sol en permanence, expire quand tu tends.",
    tracking: "reps",
  },
  {
    name: "Ramassé-porté sac lesté",
    category: "mouvement",
    equipment: ["sac_leste"],
    muscles: ["Corps entier", "Dos", "Gainage"],
    description: "Ramasser un sac au sol, le porter, le reposer proprement.",
    cues: "Charnière de hanche pour ramasser, dos plat, le sac reste proche du corps.",
    tracking: "reps_weight",
  },

  /* ------------------------------- À DEUX --------------------------------- */
  {
    name: "Passes médecine ball face à face",
    category: "duo",
    equipment: ["medecine_ball", "partenaire"],
    muscles: ["Épaules", "Gainage", "Réactivité"],
    description: "Les deux partenaires se lancent la balle en poussée poitrine.",
    cues: "Amortis avant de renvoyer, jambes fléchies, distance 2-3 m.",
    tracking: "reps",
  },
  {
    name: "Passes rotatives à deux",
    category: "duo",
    equipment: ["medecine_ball", "partenaire"],
    muscles: ["Obliques", "Hanches"],
    description: "Dos à dos, la balle tourne d'un partenaire à l'autre.",
    cues: "Pieds fixes, rotation du buste seulement. Change de sens à mi-série.",
    tracking: "reps",
  },
  {
    name: "Squat + passe",
    category: "duo",
    equipment: ["medecine_ball", "partenaire"],
    muscles: ["Jambes", "Épaules", "Cardio"],
    description: "Chacun fait un squat, puis se passe la balle en se relevant.",
    cues: "Squat complet avant chaque passe. Rythme régulier, on ne se précipite pas.",
    tracking: "reps",
  },
  {
    name: "Sit-up avec passe",
    category: "duo",
    equipment: ["medecine_ball", "partenaire"],
    muscles: ["Abdos", "Obliques"],
    description: "Face à face pieds contre pieds, la balle passe à chaque relevé.",
    cues: "Déroule le dos, la balle part quand le buste est en haut.",
    tracking: "reps",
  },
  {
    name: "Planche tape-mains",
    category: "duo",
    equipment: ["partenaire", "tapis"],
    muscles: ["Gainage", "Épaules"],
    description: "En planche face à face, chacun tape la main opposée de l'autre.",
    cues: "Bassin qui ne tourne pas, pieds un peu écartés pour la stabilité.",
    tracking: "reps",
  },
  {
    name: "Brouette",
    category: "duo",
    equipment: ["partenaire"],
    muscles: ["Épaules", "Gainage"],
    description: "Un partenaire tient les chevilles, l'autre avance sur les mains.",
    cues: "Gainage serré, ne creuse pas le bas du dos. Distance courte pour commencer.",
    tracking: "time",
  },
  {
    name: "Course résistée à l'élastique",
    category: "duo",
    equipment: ["elastique", "partenaire"],
    muscles: ["Jambes", "Explosivité"],
    description: "Un partenaire retient à l'élastique pendant que l'autre pousse en avant.",
    cues: "Buste incliné vers l'avant, appuis puissants, 10-15 m par répétition.",
    tracking: "reps",
  },
  {
    name: "Tirage élastique à deux",
    category: "duo",
    equipment: ["elastique", "partenaire"],
    muscles: ["Dos", "Gainage"],
    description: "Face à face, chacun tire l'élastique à tour de rôle ou en même temps.",
    cues: "Position stable, épaules basses, tempo commun de 2 secondes.",
    tracking: "reps",
  },
  {
    name: "Pompes avec check",
    category: "duo",
    equipment: ["partenaire", "tapis"],
    muscles: ["Pectoraux", "Gainage"],
    description: "Pompes face à face, on tape la main de l'autre en haut.",
    cues: "Le check se fait bras tendus, corps toujours gainé.",
    tracking: "reps",
  },
  {
    name: "Squat isométrique dos à dos",
    category: "duo",
    equipment: ["partenaire"],
    muscles: ["Quadriceps", "Gainage"],
    description: "Dos contre dos, on descend en chaise et on tient ensemble.",
    cues: "Appui mutuel constant, genoux à 90°, on communique pour tenir.",
    tracking: "time",
  },
  {
    name: "Relais navette à deux",
    category: "duo",
    equipment: ["partenaire"],
    muscles: ["Cardio", "Jambes"],
    description: "L'un court, l'autre gaine ou tient une position : on alterne.",
    cues: "L'échange se fait par un check. Tenue de position propre pendant l'attente.",
    tracking: "time",
  },
  {
    name: "Fentes face à face avec passe",
    category: "duo",
    equipment: ["medecine_ball", "partenaire"],
    muscles: ["Jambes", "Coordination"],
    description: "Chacun descend en fente puis se passe la balle en bas.",
    cues: "Synchronisez la descente. Genou arrière proche du sol.",
    tracking: "reps",
  },
  {
    name: "Résistance manuelle sur élévations",
    category: "duo",
    equipment: ["partenaire"],
    muscles: ["Épaules", "Bras"],
    description: "Le partenaire freine le mouvement avec les mains, montée et descente.",
    cues: "Résistance régulière, 3 secondes à la montée, 3 à la descente. On se parle.",
    tracking: "reps",
  },
  {
    name: "Burpees en miroir",
    category: "duo",
    equipment: ["partenaire"],
    muscles: ["Corps entier", "Cardio"],
    description: "Burpees synchronisés face à face, on tape dans les mains en haut.",
    cues: "Même rythme pour les deux, on ralentit ensemble plutôt que de casser la synchro.",
    tracking: "reps",
  },
  {
    name: "Planche + saut du partenaire",
    category: "duo",
    equipment: ["partenaire", "tapis"],
    muscles: ["Gainage", "Explosivité"],
    description: "L'un tient la planche, l'autre saute par-dessus à pieds joints, puis on inverse.",
    cues: "Le sauteur regarde où il atterrit, celui qui gaine reste bien serré.",
    tracking: "reps",
  },

  /* -------------------------------- GAINAGE ------------------------------- */
  {
    name: "Planche",
    category: "core",
    equipment: ["tapis"],
    muscles: ["Gainage", "Abdos profonds"],
    description: "Position de gainage sur les avant-bras et les pointes de pieds.",
    cues: "Ligne droite talons-tête, fessiers serrés, nombril rentré, respire.",
    tracking: "time",
  },
  {
    name: "Planche latérale",
    category: "core",
    equipment: ["tapis"],
    muscles: ["Obliques", "Gainage"],
    description: "Gainage sur un avant-bras, corps de profil.",
    cues: "Hanche haute, coude sous l'épaule, ne descends pas le bassin.",
    tracking: "time",
  },
  {
    name: "Planche dynamique (haut-bas)",
    category: "core",
    equipment: ["tapis"],
    muscles: ["Gainage", "Épaules", "Triceps"],
    description: "Passage de la planche sur les avant-bras à la planche sur les mains.",
    cues: "Bassin le plus stable possible, alterne le bras qui démarre.",
    tracking: "reps",
  },
  {
    name: "Hollow hold",
    category: "core",
    equipment: ["tapis"],
    muscles: ["Abdos profonds"],
    description: "Allongée sur le dos, bras et jambes décollés en forme de banane.",
    cues: "Bas du dos plaqué au sol : si ça décolle, remonte les jambes.",
    tracking: "time",
  },
  {
    name: "Dead bug",
    category: "core",
    equipment: ["tapis"],
    muscles: ["Abdos profonds", "Gainage"],
    description: "Bras et jambe opposés qui se déploient lentement en gardant le dos plaqué.",
    cues: "Expire en tendant, très lent. Qualité avant quantité.",
    tracking: "reps",
  },
  {
    name: "Bird dog",
    category: "core",
    equipment: ["tapis"],
    muscles: ["Lombaires", "Fessiers", "Gainage"],
    description: "À quatre pattes, on tend le bras et la jambe opposés.",
    cues: "Bassin qui ne bascule pas, pause de 2 s en extension.",
    tracking: "reps",
  },
  {
    name: "Mountain climbers",
    category: "core",
    equipment: ["tapis"],
    muscles: ["Gainage", "Cardio", "Fléchisseurs de hanche"],
    description: "En planche, les genoux viennent alternativement vers la poitrine.",
    cues: "Bassin bas et stable, épaules au-dessus des mains, rythme soutenu.",
    tracking: "time",
  },
  {
    name: "Relevés de jambes",
    category: "core",
    equipment: ["tapis"],
    muscles: ["Abdos"],
    description: "Allongée, jambes tendues qui montent et descendent sans toucher le sol.",
    cues: "Mains sous les fesses si le bas du dos décolle. Descente contrôlée.",
    tracking: "reps",
  },
  {
    name: "Roulette abdos",
    category: "core",
    equipment: ["roue_abdos"],
    muscles: ["Abdos profonds", "Gainage", "Dos"],
    description: "Depuis les genoux, on déroule la roue vers l'avant puis on revient.",
    cues: "Dos qui ne se creuse jamais. Amplitude courte au début.",
    tracking: "reps",
  },
  {
    name: "Pallof press",
    category: "core",
    equipment: ["elastique"],
    muscles: ["Obliques", "Gainage"],
    description: "Élastique tendu sur le côté, on pousse les bras devant en résistant à la rotation.",
    cues: "Le buste ne tourne pas d'un millimètre. Tiens 2 s bras tendus.",
    tracking: "reps",
  },
  {
    name: "Superman",
    category: "core",
    equipment: ["tapis"],
    muscles: ["Lombaires", "Fessiers"],
    description: "À plat ventre, bras et jambes décollés simultanément.",
    cues: "Regard vers le sol, allonge-toi plutôt que de cambrer.",
    tracking: "time",
  },
  {
    name: "Gainage avec charge sur le dos",
    category: "core",
    equipment: ["disque", "tapis"],
    muscles: ["Gainage"],
    description: "Planche classique avec un disque posé sur le haut du dos.",
    cues: "Charge posée par le partenaire. Position parfaite avant d'ajouter du poids.",
    tracking: "time",
  },

  /* -------------------------------- CARDIO -------------------------------- */
  {
    name: "Rameur — intervalles",
    category: "cardio",
    equipment: ["rameur"],
    muscles: ["Corps entier", "Cardio"],
    description: "Séries de rame intense entrecoupées de récupération active.",
    cues: "Garde une cadence stable, pousse fort avec les jambes. Note ta distance.",
    tracking: "time_distance",
  },
  {
    name: "Vélo — intervalles",
    category: "cardio",
    equipment: ["velo"],
    muscles: ["Jambes", "Cardio"],
    description: "Alternance sprint / récupération sur vélo.",
    cues: "Résistance suffisante pour ne pas pédaler dans le vide. Récup vraiment facile.",
    tracking: "time_distance",
  },
  {
    name: "Burpees",
    category: "cardio",
    equipment: ["aucun"],
    muscles: ["Corps entier", "Cardio"],
    description: "Descente au sol, planche, remontée, saut.",
    cues: "Trouve ton rythme et tiens-le. Version sans saut si besoin.",
    tracking: "reps",
  },
  {
    name: "Battle rope",
    category: "cardio",
    equipment: ["corde_ondulatoire"],
    muscles: ["Épaules", "Bras", "Cardio"],
    description: "Ondulations rapides des cordes, en alterné ou simultané.",
    cues: "Genoux fléchis, gainage serré, l'onde doit aller jusqu'à l'ancrage.",
    tracking: "time",
  },
  {
    name: "Corde à sauter — intervalles",
    category: "cardio",
    equipment: ["corde_a_sauter"],
    muscles: ["Mollets", "Cardio"],
    description: "Sauts rapides en séries chronométrées.",
    cues: "Sauts bas et rapides, la corde passe juste sous les pieds.",
    tracking: "time",
  },
  {
    name: "Navettes (shuttle run)",
    category: "cardio",
    equipment: ["aucun"],
    muscles: ["Jambes", "Cardio"],
    description: "Allers-retours entre deux repères avec changement de direction.",
    cues: "Freine sur 2-3 appuis, touche le sol au demi-tour, repars fort.",
    tracking: "time",
  },
  {
    name: "Sprint sur place",
    category: "cardio",
    equipment: ["aucun"],
    muscles: ["Jambes", "Cardio"],
    description: "Course sur place à intensité maximale sur un temps court.",
    cues: "Fréquence maximale, bras actifs. 15-30 s max par série.",
    tracking: "time",
  },
  {
    name: "Marche en côte / tapis incliné",
    category: "cardio",
    equipment: ["aucun"],
    muscles: ["Fessiers", "Cardio"],
    description: "Marche rapide en pente, sans se tenir aux poignées.",
    cues: "Buste droit, grandes foulées, respiration nasale si possible.",
    tracking: "time_distance",
  },
  {
    name: "Circuit métabolique",
    category: "cardio",
    equipment: ["aucun"],
    muscles: ["Corps entier", "Cardio"],
    description: "Enchaînement de plusieurs mouvements sans repos, en boucle.",
    cues: "Choisis un rythme que tu peux tenir sur tous les tours.",
    tracking: "time",
  },
  {
    name: "Kettlebell swing — format cardio",
    category: "cardio",
    equipment: ["kettlebell"],
    muscles: ["Fessiers", "Cardio"],
    description: "Swings en séries longues type EMOM ou Tabata.",
    cues: "Respiration synchronisée : expire en haut. Ne perds pas la technique avec la fatigue.",
    tracking: "reps_weight",
  },

  /* ----------------------------- EXPLOSIVITÉ ------------------------------ */
  {
    name: "Box jump",
    category: "plyo",
    equipment: ["box"],
    muscles: ["Quadriceps", "Fessiers", "Explosivité"],
    description: "Saut à pieds joints sur une box.",
    cues: "Réception souple au milieu de la box, redescends en marchant, jamais en sautant.",
    tracking: "reps",
  },
  {
    name: "Squat sauté",
    category: "plyo",
    equipment: ["aucun"],
    muscles: ["Quadriceps", "Fessiers"],
    description: "Squat suivi d'un saut vertical maximal.",
    cues: "Réception silencieuse, enchaîne directement sur le squat suivant.",
    tracking: "reps",
  },
  {
    name: "Saut en longueur (broad jump)",
    category: "plyo",
    equipment: ["aucun"],
    muscles: ["Fessiers", "Ischio-jambiers", "Explosivité"],
    description: "Saut horizontal maximal à pieds joints.",
    cues: "Balancier des bras, projection vers l'avant, réception genoux fléchis.",
    tracking: "reps",
  },
  {
    name: "Skater jumps",
    category: "plyo",
    equipment: ["aucun"],
    muscles: ["Fessiers", "Moyen fessier", "Équilibre"],
    description: "Bonds latéraux d'un pied sur l'autre, comme un patineur.",
    cues: "Stabilise 1 s à chaque réception, genou dans l'axe du pied.",
    tracking: "reps",
  },
  {
    name: "Fentes sautées",
    category: "plyo",
    equipment: ["aucun"],
    muscles: ["Quadriceps", "Fessiers"],
    description: "Changement de jambe en l'air depuis la position de fente.",
    cues: "Amorti en descendant, buste droit, ne cogne pas le genou au sol.",
    tracking: "reps",
  },
  {
    name: "Step-up sauté",
    category: "plyo",
    equipment: ["box", "step"],
    muscles: ["Quadriceps", "Fessiers"],
    description: "Montée explosive sur la box avec changement de pied en l'air.",
    cues: "Box basse, rythme régulier, regarde la box.",
    tracking: "reps",
  },
  {
    name: "Tuck jumps",
    category: "plyo",
    equipment: ["aucun"],
    muscles: ["Abdos", "Jambes"],
    description: "Saut vertical avec les genoux ramenés vers la poitrine.",
    cues: "Séries courtes (5-8 reps), qualité de réception avant tout.",
    tracking: "reps",
  },
  {
    name: "Pompes claquées",
    category: "plyo",
    equipment: ["tapis"],
    muscles: ["Pectoraux", "Explosivité"],
    description: "Pompe explosive, les mains décollent du sol.",
    cues: "Version genoux ou surélevée au début. Amortis à la réception.",
    tracking: "reps",
  },

  /* ------------------------------- MOBILITÉ ------------------------------- */
  {
    name: "World's greatest stretch",
    category: "mobilite",
    equipment: ["tapis"],
    muscles: ["Hanches", "Dos", "Ischio-jambiers"],
    description: "Fente profonde, coude au sol, puis rotation du buste vers le ciel.",
    cues: "Respire dans la position, 3 respirations par côté.",
    tracking: "reps",
  },
  {
    name: "90/90 hanches",
    category: "mobilite",
    equipment: ["tapis"],
    muscles: ["Hanches"],
    description: "Assise, jambes à 90° devant et sur le côté, on bascule d'un côté à l'autre.",
    cues: "Dos droit, mouvement lent, ne force pas sur les genoux.",
    tracking: "reps",
  },
  {
    name: "Chat-vache",
    category: "mobilite",
    equipment: ["tapis"],
    muscles: ["Colonne vertébrale"],
    description: "À quatre pattes, alternance dos rond / dos creux.",
    cues: "Synchronise avec la respiration : inspire en creusant, expire en arrondissant.",
    tracking: "reps",
  },
  {
    name: "Ouverture thoracique",
    category: "mobilite",
    equipment: ["tapis"],
    muscles: ["Dos", "Pectoraux"],
    description: "Allongée sur le côté, le bras du dessus s'ouvre vers l'arrière.",
    cues: "Genoux qui restent collés au sol, suis la main du regard.",
    tracking: "reps",
  },
  {
    name: "Étirement psoas",
    category: "mobilite",
    equipment: ["tapis"],
    muscles: ["Psoas", "Quadriceps"],
    description: "Fente genou au sol, bassin poussé vers l'avant.",
    cues: "Rétroversion du bassin (fessier serré) pour vraiment sentir l'avant de la hanche.",
    tracking: "time",
  },
  {
    name: "Étirement ischio-jambiers",
    category: "mobilite",
    equipment: ["tapis"],
    muscles: ["Ischio-jambiers"],
    description: "Jambe tendue devant, on pousse les fesses vers l'arrière.",
    cues: "Dos plat, la sensation doit être dans le muscle, jamais derrière le genou.",
    tracking: "time",
  },
  {
    name: "Pigeon",
    category: "mobilite",
    equipment: ["tapis"],
    muscles: ["Fessiers", "Hanches"],
    description: "Jambe avant repliée, jambe arrière tendue, buste qui descend.",
    cues: "Coussin sous la fesse si c'est trop intense. 60-90 s par côté.",
    tracking: "time",
  },
  {
    name: "Squat profond tenu",
    category: "mobilite",
    equipment: ["aucun"],
    muscles: ["Hanches", "Chevilles"],
    description: "Position accroupie basse tenue, coudes qui écartent les genoux.",
    cues: "Talons au sol si possible, sinon surélève-les. Respire profondément.",
    tracking: "time",
  },
  {
    name: "Étirement épaules au mur",
    category: "mobilite",
    equipment: ["aucun"],
    muscles: ["Épaules", "Pectoraux"],
    description: "Main au mur, on fait pivoter le buste dans le sens opposé.",
    cues: "Bras à hauteur d'épaule, rotation lente, 30 s par côté.",
    tracking: "time",
  },
  {
    name: "Respiration et retour au calme",
    category: "mobilite",
    equipment: ["tapis"],
    muscles: ["Système nerveux"],
    description: "Allongée, respiration lente pour faire redescendre le cardiaque.",
    cues: "Inspire 4 s, bloque 2 s, expire 6 s. Ferme les yeux.",
    tracking: "time",
  },
];
